// Stub: quiz sound effects (no-op)
export function playKBCIntro(): void {}
export function playQuestionReveal(): void {}
export function playOptionSelect(): void {}
export function playLockKiyaJaye(): void {}
export function playCorrectAnswer(): void {}
export function playWrongAnswer(): void {}
export function playTimerTick(): void {}
export function playTimerWarning(): void {}
export function playLifelineUsed(): void {}
export function playHeartLost(): void {}
export function playGameOver(): void {}
export function playWinFanfare(): void {}
export function playPerfectScore(): void {}
export function playStreakFire(): void {}
export function playXPGain(): void {}
export function playButtonPress(): void {}
export function playSlideTransition(): void {}
export function playCountdownBeep(): void {}
