import { db } from '@/lib/db';

/**
 * Seed quiz categories and questions for all departments
 * Run: bun run seed-quiz (or call from an API route)
 */

const CATEGORIES = [
  // ============================================================
  // CSE DEPARTMENT
  // ============================================================
  {
    name: 'C++ Programming',
    department: 'CSE',
    icon: '💻',
    difficulty: 'MEDIUM',
    description: 'Core C++ programming concepts and syntax',
    questions: [
      { question: 'Which keyword is used to allocate memory dynamically in C++?', optionA: 'malloc', optionB: 'new', optionC: 'alloc', optionD: 'create', correctOption: 'B', explanation: 'The "new" keyword is used for dynamic memory allocation in C++.', difficulty: 'EASY' },
      { question: 'What is the output of: cout << 5/2;', optionA: '2.5', optionB: '2', optionC: '3', optionD: 'Error', correctOption: 'B', explanation: 'Integer division in C++ truncates the decimal part.', difficulty: 'EASY' },
      { question: 'Which header file is needed for input/output in C++?', optionA: '<stdio.h>', optionB: '<iostream>', optionC: '<conio.h>', optionD: '<fstream>', correctOption: 'B', explanation: '<iostream> provides cin and cout objects for I/O.', difficulty: 'EASY' },
      { question: 'What does the "virtual" keyword do in C++?', optionA: 'Makes variable constant', optionB: 'Enables polymorphism', optionC: 'Creates static method', optionD: 'Allocates memory', correctOption: 'B', explanation: 'Virtual enables runtime polymorphism via vtable.', difficulty: 'MEDIUM' },
      { question: 'Which STL container provides key-value pairs with unique keys?', optionA: 'vector', optionB: 'list', optionC: 'map', optionD: 'set', correctOption: 'C', explanation: 'std::map stores key-value pairs with unique keys in sorted order.', difficulty: 'MEDIUM' },
      { question: 'What is the time complexity of binary search?', optionA: 'O(n)', optionB: 'O(log n)', optionC: 'O(n²)', optionD: 'O(1)', correctOption: 'B', explanation: 'Binary search divides the search space in half each iteration.', difficulty: 'MEDIUM' },
      { question: 'Which operator is used for pointer dereferencing in C++?', optionA: '&', optionB: '*', optionC: '#', optionD: '@', correctOption: 'B', explanation: 'The * operator dereferences a pointer to access the value at the memory address.', difficulty: 'EASY' },
      { question: 'What is a destructor in C++?', optionA: 'A function to initialize objects', optionB: 'A function called when object is created', optionC: 'A function called when object is destroyed', optionD: 'A function to copy objects', correctOption: 'C', explanation: 'Destructors are called automatically when an object goes out of scope or is deleted.', difficulty: 'MEDIUM' },
      { question: 'Which of these is NOT a C++ access modifier?', optionA: 'public', optionB: 'private', optionC: 'protected', optionD: 'internal', correctOption: 'D', explanation: 'internal is a C# access modifier. C++ uses public, private, protected.', difficulty: 'EASY' },
      { question: 'What does "std::" represent in C++?', optionA: 'Standard library', optionB: 'System function', optionC: 'Static method', optionD: 'String type', correctOption: 'A', explanation: 'std:: is the namespace for the C++ Standard Library.', difficulty: 'EASY' },
    ],
  },
  {
    name: 'Python Programming',
    department: 'CSE',
    icon: '🐍',
    difficulty: 'MEDIUM',
    description: 'Python fundamentals and advanced concepts',
    questions: [
      { question: 'What is the output of: print(type([]))?', optionA: '<class dict>', optionB: '<class list>', optionC: '<class tuple>', optionD: '<class set>', correctOption: 'B', explanation: '[] creates an empty list in Python.', difficulty: 'EASY' },
      { question: 'Which keyword is used to define a function in Python?', optionA: 'function', optionB: 'func', optionC: 'def', optionD: 'define', correctOption: 'C', explanation: 'def is the keyword used to define functions in Python.', difficulty: 'EASY' },
      { question: 'What does "self" refer to in a Python class?', optionA: 'Class name', optionB: 'Current instance', optionC: 'Parent class', optionD: 'Module', correctOption: 'B', explanation: 'self refers to the current instance of the class.', difficulty: 'MEDIUM' },
      { question: 'Which data structure is immutable in Python?', optionA: 'list', optionB: 'dict', optionC: 'set', optionD: 'tuple', correctOption: 'D', explanation: 'Tuples are immutable sequences in Python.', difficulty: 'EASY' },
      { question: 'What is a decorator in Python?', optionA: 'A GUI component', optionB: 'A function that modifies another function', optionC: 'A type of loop', optionD: 'A variable modifier', correctOption: 'B', explanation: 'Decorators wrap a function to extend its behavior without modifying it.', difficulty: 'HARD' },
      { question: 'What does "len()" do in Python?', optionA: 'Returns length of object', optionB: 'Creates a list', optionC: 'Converts to integer', optionD: 'Sorts a list', correctOption: 'A', explanation: 'len() returns the number of items in an object.', difficulty: 'EASY' },
      { question: 'Which module is used for regular expressions in Python?', optionA: 'regex', optionB: 're', optionC: 'regexp', optionD: 'pattern', correctOption: 'B', explanation: 'The re module provides regular expression operations in Python.', difficulty: 'MEDIUM' },
      { question: 'What is the output of: print(2 ** 3)?', optionA: '6', optionB: '8', optionC: '5', optionD: 'Error', correctOption: 'B', explanation: '** is the exponentiation operator in Python. 2**3 = 8.', difficulty: 'EASY' },
      { question: 'What is a generator in Python?', optionA: 'A random number creator', optionB: 'A function that yields values lazily', optionC: 'A class constructor', optionD: 'A file reader', correctOption: 'B', explanation: 'Generators use yield to produce values one at a time, lazily.', difficulty: 'HARD' },
      { question: 'Which method is used to add an element to a set in Python?', optionA: 'append()', optionB: 'insert()', optionC: 'add()', optionD: 'push()', correctOption: 'C', explanation: 'set.add() adds an element to a set.', difficulty: 'MEDIUM' },
    ],
  },
  {
    name: 'Data Structures',
    department: 'CSE',
    icon: '🏗️',
    difficulty: 'MEDIUM',
    description: 'Fundamental data structures and algorithms',
    questions: [
      { question: 'What is the worst-case time complexity of QuickSort?', optionA: 'O(n log n)', optionB: 'O(n)', optionC: 'O(n²)', optionD: 'O(log n)', correctOption: 'C', explanation: 'QuickSort worst case is O(n²) when the pivot selection is poor.', difficulty: 'MEDIUM' },
      { question: 'Which data structure uses LIFO principle?', optionA: 'Queue', optionB: 'Stack', optionC: 'Array', optionD: 'Linked List', correctOption: 'B', explanation: 'Stack follows Last In First Out (LIFO) principle.', difficulty: 'EASY' },
      { question: 'What is a binary search tree?', optionA: 'A tree with max 3 children', optionB: 'A tree where left < root < right', optionC: 'A complete binary tree', optionD: 'A balanced tree', correctOption: 'B', explanation: 'BST property: left subtree < root < right subtree for all nodes.', difficulty: 'MEDIUM' },
      { question: 'Which data structure is best for implementing a priority queue?', optionA: 'Array', optionB: 'Linked List', optionC: 'Heap', optionD: 'Stack', correctOption: 'C', explanation: 'Heaps efficiently support extract-min/max operations needed for priority queues.', difficulty: 'MEDIUM' },
      { question: 'What is the time complexity of inserting into a hash table?', optionA: 'O(1) average', optionB: 'O(n)', optionC: 'O(log n)', optionD: 'O(n²)', correctOption: 'A', explanation: 'Hash table insert is O(1) average case, O(n) worst case with collisions.', difficulty: 'EASY' },
      { question: 'Which traversal visits root before children?', optionA: 'Inorder', optionB: 'Postorder', optionC: 'Preorder', optionD: 'Level order', correctOption: 'C', explanation: 'Preorder traversal visits root, then left subtree, then right subtree.', difficulty: 'MEDIUM' },
      { question: 'What is a graph with no cycles called?', optionA: 'Complete graph', optionB: 'Directed graph', optionC: 'Tree/Acyclic graph', optionD: 'Weighted graph', correctOption: 'C', explanation: 'A graph with no cycles is called an acyclic graph (a tree if connected).', difficulty: 'EASY' },
      { question: 'Which algorithm finds the shortest path in a weighted graph?', optionA: 'BFS', optionB: 'DFS', optionC: "Dijkstra's algorithm", optionD: 'Binary search', correctOption: 'C', explanation: "Dijkstra's algorithm finds shortest paths from source to all vertices.", difficulty: 'MEDIUM' },
      { question: 'What is the space complexity of merge sort?', optionA: 'O(1)', optionB: 'O(n)', optionC: 'O(log n)', optionD: 'O(n²)', correctOption: 'B', explanation: 'Merge sort requires O(n) auxiliary space for the merge operation.', difficulty: 'MEDIUM' },
      { question: 'Which data structure uses FIFO principle?', optionA: 'Stack', optionB: 'Queue', optionC: 'Tree', optionD: 'Graph', correctOption: 'B', explanation: 'Queue follows First In First Out (FIFO) principle.', difficulty: 'EASY' },
    ],
  },
  {
    name: 'Operating Systems',
    department: 'CSE',
    icon: '🖥️',
    difficulty: 'MEDIUM',
    description: 'Process management, memory management, file systems, and scheduling',
    questions: [
      { question: 'What is a deadlock in operating systems?', optionA: 'A process that runs forever', optionB: 'A situation where processes are blocked waiting for each other', optionC: 'A system crash', optionD: 'A memory leak', correctOption: 'B', explanation: 'Deadlock occurs when two or more processes are unable to proceed because each is waiting for the other to release a resource.', difficulty: 'MEDIUM' },
      { question: 'Which scheduling algorithm may cause starvation?', optionA: 'Round Robin', optionB: 'Shortest Job First (SJF)', optionC: 'First Come First Served (FCFS)', optionD: 'Fair Share', correctOption: 'B', explanation: 'SJF can cause starvation because long processes may never execute if short processes keep arriving.', difficulty: 'MEDIUM' },
      { question: 'What is virtual memory?', optionA: 'A type of RAM', optionB: 'Memory management technique using disk space as extension of RAM', optionC: 'A hardware component', optionD: 'Cache memory', correctOption: 'B', explanation: 'Virtual memory uses disk storage to extend available RAM, allowing programs to use more memory than physically available.', difficulty: 'EASY' },
      { question: 'What is a page fault?', optionA: 'A hardware error', optionB: 'An interrupt when a program accesses a page not in physical memory', optionC: 'A disk read error', optionD: 'A segmentation fault', correctOption: 'B', explanation: 'A page fault occurs when the CPU tries to access a virtual memory page that is not loaded in physical RAM.', difficulty: 'MEDIUM' },
      { question: 'Which of the following is NOT a condition for deadlock?', optionA: 'Mutual exclusion', optionB: 'Hold and wait', optionC: 'Preemption', optionD: 'Circular wait', correctOption: 'C', explanation: 'The four deadlock conditions are: mutual exclusion, hold and wait, no preemption, and circular wait. Preemption prevents deadlock.', difficulty: 'HARD' },
      { question: 'What is the purpose of the TLB (Translation Lookaside Buffer)?', optionA: 'To store frequently accessed disk blocks', optionB: 'To cache page table entries for faster address translation', optionC: 'To manage process scheduling', optionD: 'To handle interrupts', correctOption: 'B', explanation: 'The TLB is a hardware cache that stores recent virtual-to-physical address translations to speed up memory access.', difficulty: 'HARD' },
      { question: 'In Round Robin scheduling, what determines the time a process gets to execute?', optionA: 'Priority', optionB: 'Burst time', optionC: 'Time quantum (time slice)', optionD: 'Arrival time', correctOption: 'C', explanation: 'Round Robin assigns a fixed time quantum to each process in a cyclic manner.', difficulty: 'EASY' },
      { question: 'What is thrashing?', optionA: 'A disk fragmentation issue', optionB: 'Excessive paging that degrades system performance', optionC: 'A CPU scheduling problem', optionD: 'A memory allocation error', correctOption: 'B', explanation: 'Thrashing occurs when a system spends more time paging (swapping pages in/out) than executing actual code.', difficulty: 'HARD' },
      { question: 'Which file allocation method suffers from external fragmentation?', optionA: 'Contiguous allocation', optionB: 'Linked allocation', optionC: 'Indexed allocation', optionD: 'Both B and C', correctOption: 'A', explanation: 'Contiguous allocation can lead to external fragmentation as files are created and deleted, leaving scattered free blocks.', difficulty: 'MEDIUM' },
      { question: 'What is a semaphore?', optionA: 'A data structure for file storage', optionB: 'A synchronization primitive used to control access to shared resources', optionC: 'A type of process', optionD: 'A memory allocation scheme', correctOption: 'B', explanation: 'Semaphores are integer variables used for signaling between processes to manage concurrent access to shared resources.', difficulty: 'MEDIUM' },
    ],
  },
  {
    name: 'Database Management',
    department: 'CSE',
    icon: '🗄️',
    difficulty: 'MEDIUM',
    description: 'SQL, normalization, indexing, transactions, and ER diagrams',
    questions: [
      { question: 'What does SQL stand for?', optionA: 'Structured Query Language', optionB: 'Simple Query Language', optionC: 'Standard Query Logic', optionD: 'Sequential Query Language', correctOption: 'A', explanation: 'SQL stands for Structured Query Language, used for managing relational databases.', difficulty: 'EASY' },
      { question: 'What is the third normal form (3NF)?', optionA: 'No repeating groups', optionB: 'No partial dependencies and no transitive dependencies', optionC: 'Every determinant is a candidate key', optionD: 'No multivalued dependencies', correctOption: 'B', explanation: '3NF requires 2NF plus no transitive dependencies — non-key attributes must not depend on other non-key attributes.', difficulty: 'MEDIUM' },
      { question: 'Which SQL command is used to retrieve data from a database?', optionA: 'INSERT', optionB: 'UPDATE', optionC: 'SELECT', optionD: 'DELETE', correctOption: 'C', explanation: 'SELECT is the SQL command used to query and retrieve data from one or more tables.', difficulty: 'EASY' },
      { question: 'What is a foreign key?', optionA: 'A key used for encryption', optionB: 'A field that uniquely identifies a record in another table', optionC: 'A primary key in another name', optionD: 'A backup key', correctOption: 'B', explanation: 'A foreign key is a column that creates a link between two tables by referencing the primary key of another table.', difficulty: 'EASY' },
      { question: 'What is an index in a database?', optionA: 'A table of contents for faster data retrieval', optionB: 'A backup of the database', optionC: 'A constraint on data', optionD: 'A type of join', correctOption: 'A', explanation: 'An index is a data structure that improves the speed of data retrieval operations on a table.', difficulty: 'MEDIUM' },
      { question: 'What is a transaction in DBMS?', optionA: 'A single SQL query', optionB: 'A logical unit of work that must be completed entirely or not at all', optionC: 'A database backup operation', optionD: 'A user login process', correctOption: 'B', explanation: 'A transaction is a sequence of operations performed as a single logical unit of work, following ACID properties.', difficulty: 'MEDIUM' },
      { question: 'Which of the following is NOT an ACID property?', optionA: 'Atomicity', optionB: 'Consistency', optionC: 'Integrity', optionD: 'Durability', correctOption: 'C', explanation: 'ACID stands for Atomicity, Consistency, Isolation, and Durability. Integrity is not one of them.', difficulty: 'MEDIUM' },
      { question: 'What type of join returns all rows from both tables, matching where possible?', optionA: 'INNER JOIN', optionB: 'LEFT JOIN', optionC: 'RIGHT JOIN', optionD: 'FULL OUTER JOIN', correctOption: 'D', explanation: 'FULL OUTER JOIN returns all rows from both tables, with NULLs where there is no match in either table.', difficulty: 'MEDIUM' },
      { question: 'In an ER diagram, what does a diamond shape represent?', optionA: 'Entity', optionB: 'Attribute', optionC: 'Relationship', optionD: 'Key', correctOption: 'C', explanation: 'In ER diagrams, diamonds represent relationships between entities, rectangles represent entities, and ovals represent attributes.', difficulty: 'EASY' },
      { question: 'What is the purpose of the HAVING clause in SQL?', optionA: 'To filter rows before grouping', optionB: 'To filter groups after the GROUP BY clause', optionC: 'To sort the result set', optionD: 'To join multiple tables', correctOption: 'B', explanation: 'HAVING filters the results of GROUP BY, while WHERE filters rows before grouping occurs.', difficulty: 'HARD' },
    ],
  },
  {
    name: 'Networking',
    department: 'CSE',
    icon: '🌐',
    difficulty: 'MEDIUM',
    description: 'OSI model, TCP/IP, protocols, routing, and subnetting',
    questions: [
      { question: 'How many layers are in the OSI model?', optionA: '4', optionB: '5', optionC: '7', optionD: '6', correctOption: 'C', explanation: 'The OSI (Open Systems Interconnection) model has 7 layers: Physical, Data Link, Network, Transport, Session, Presentation, Application.', difficulty: 'EASY' },
      { question: 'Which protocol is used for secure web browsing?', optionA: 'HTTP', optionB: 'FTP', optionC: 'HTTPS', optionD: 'SMTP', correctOption: 'C', explanation: 'HTTPS (HTTP Secure) uses SSL/TLS encryption to provide secure communication over the internet.', difficulty: 'EASY' },
      { question: 'What is the purpose of DNS?', optionA: 'To encrypt data', optionB: 'To translate domain names to IP addresses', optionC: 'To route packets', optionD: 'To manage network bandwidth', correctOption: 'B', explanation: 'DNS (Domain Name System) translates human-readable domain names like www.example.com into IP addresses.', difficulty: 'EASY' },
      { question: 'Which layer of the OSI model is responsible for routing?', optionA: 'Data Link Layer', optionB: 'Transport Layer', optionC: 'Network Layer', optionD: 'Session Layer', correctOption: 'C', explanation: 'The Network Layer (Layer 3) handles logical addressing and routing of packets between networks.', difficulty: 'MEDIUM' },
      { question: 'What is subnetting?', optionA: 'Splitting a network into smaller sub-networks', optionB: 'Connecting multiple networks', optionC: 'Encrypting network traffic', optionD: 'Increasing bandwidth', correctOption: 'A', explanation: 'Subnetting divides a large network into smaller, more efficient sub-networks to improve performance and security.', difficulty: 'MEDIUM' },
      { question: 'Which transport layer protocol is connectionless?', optionA: 'TCP', optionB: 'UDP', optionC: 'FTP', optionD: 'HTTP', correctOption: 'B', explanation: 'UDP (User Datagram Protocol) is connectionless — it sends data without establishing a connection, offering speed over reliability.', difficulty: 'MEDIUM' },
      { question: 'What is the MAC address?', optionA: 'A logical address assigned by the network', optionB: 'A physical address burned into the network interface card', optionC: 'An IP address', optionD: 'A domain name', correctOption: 'B', explanation: 'A MAC (Media Access Control) address is a unique 48-bit hardware address assigned to a NIC by the manufacturer.', difficulty: 'MEDIUM' },
      { question: 'What is NAT (Network Address Translation)?', optionA: 'A routing protocol', optionB: 'A method of remapping one IP address space into another', optionC: 'A DNS service', optionD: 'A firewall technique', correctOption: 'B', explanation: 'NAT maps private IP addresses to a public IP address, allowing multiple devices to share a single public IP for internet access.', difficulty: 'HARD' },
      { question: 'Which protocol is used to send email?', optionA: 'POP3', optionB: 'IMAP', optionC: 'SMTP', optionD: 'SNMP', correctOption: 'C', explanation: 'SMTP (Simple Mail Transfer Protocol) is the standard protocol for sending email messages between servers.', difficulty: 'EASY' },
      { question: 'What is a three-way handshake?', optionA: 'A password exchange method', optionB: 'TCP connection establishment: SYN, SYN-ACK, ACK', optionC: 'A DNS query process', optionD: 'A routing algorithm', correctOption: 'B', explanation: 'The TCP three-way handshake establishes a connection: client sends SYN, server responds with SYN-ACK, client replies with ACK.', difficulty: 'HARD' },
    ],
  },
  {
    name: 'Machine Learning',
    department: 'CSE',
    icon: '🤖',
    difficulty: 'MEDIUM',
    description: 'Supervised/unsupervised learning, neural networks, and ML algorithms',
    questions: [
      { question: 'What is the difference between supervised and unsupervised learning?', optionA: 'Supervised uses labeled data; unsupervised uses unlabeled data', optionB: 'Supervised is faster; unsupervised is slower', optionC: 'Supervised uses images; unsupervised uses text', optionD: 'There is no difference', correctOption: 'A', explanation: 'Supervised learning trains on labeled data (input-output pairs), while unsupervised learning finds patterns in unlabeled data.', difficulty: 'EASY' },
      { question: 'Which algorithm is commonly used for classification tasks?', optionA: 'Linear Regression', optionB: 'K-Means Clustering', optionC: 'Decision Tree', optionD: 'PCA', correctOption: 'C', explanation: 'Decision Trees are commonly used for classification tasks by splitting data based on feature values.', difficulty: 'EASY' },
      { question: 'What is overfitting in machine learning?', optionA: 'The model performs well on both training and test data', optionB: 'The model performs well on training data but poorly on unseen data', optionC: 'The model fails to learn from training data', optionD: 'The model is too simple', correctOption: 'B', explanation: 'Overfitting occurs when a model learns noise and details of training data to the extent that it negatively impacts performance on new data.', difficulty: 'MEDIUM' },
      { question: 'What is the activation function used in the output layer of a binary classification neural network?', optionA: 'ReLU', optionB: 'Softmax', optionC: 'Sigmoid', optionD: 'Tanh', correctOption: 'C', explanation: 'Sigmoid outputs values between 0 and 1, making it ideal for binary classification probabilities.', difficulty: 'MEDIUM' },
      { question: 'What is gradient descent?', optionA: 'A data preprocessing technique', optionB: 'An optimization algorithm to minimize the loss function', optionC: 'A type of neural network', optionD: 'A feature selection method', correctOption: 'B', explanation: 'Gradient descent iteratively adjusts model parameters in the direction that reduces the loss function.', difficulty: 'MEDIUM' },
      { question: 'Which unsupervised algorithm groups similar data points together?', optionA: 'Logistic Regression', optionB: 'Support Vector Machine', optionC: 'K-Means Clustering', optionD: 'Random Forest', correctOption: 'C', explanation: 'K-Means is an unsupervised clustering algorithm that partitions data into K clusters based on similarity.', difficulty: 'EASY' },
      { question: 'What is the "kernel trick" in SVM?', optionA: 'A method to speed up training', optionB: 'A technique to transform data into higher dimensions without computing coordinates', optionC: 'A way to reduce model size', optionD: 'A preprocessing step', correctOption: 'B', explanation: 'The kernel trick allows SVM to create non-linear decision boundaries by implicitly mapping data to higher-dimensional space.', difficulty: 'HARD' },
      { question: 'What is a confusion matrix used for?', optionA: 'To organize training data', optionB: 'To evaluate classification model performance', optionC: 'To normalize data', optionD: 'To reduce dimensionality', correctOption: 'B', explanation: 'A confusion matrix shows True Positives, True Negatives, False Positives, and False Negatives to evaluate classifier performance.', difficulty: 'MEDIUM' },
      { question: 'What does the "learning rate" hyperparameter control?', optionA: 'The number of training epochs', optionB: 'The size of steps taken during gradient descent', optionC: 'The number of hidden layers', optionD: 'The batch size', correctOption: 'B', explanation: 'The learning rate determines how much the model weights are updated in response to the estimated error each iteration.', difficulty: 'HARD' },
      { question: 'What is the main advantage of a Random Forest over a single Decision Tree?', optionA: 'Faster training time', optionB: 'Uses less memory', optionC: 'Reduces overfitting by averaging multiple trees', optionD: 'Requires fewer features', correctOption: 'C', explanation: 'Random Forest reduces overfitting by building multiple decision trees on random subsets and averaging their predictions (ensemble learning).', difficulty: 'HARD' },
    ],
  },

  // ============================================================
  // LLB DEPARTMENT
  // ============================================================
  {
    name: 'Constitutional Law',
    department: 'LLB',
    icon: '⚖️',
    difficulty: 'MEDIUM',
    description: 'Fundamentals of constitutional law and governance',
    questions: [
      { question: 'What is the supreme law of the land in most democracies?', optionA: 'Criminal Code', optionB: 'Constitution', optionC: 'Civil Law', optionD: 'Administrative Law', correctOption: 'B', explanation: 'The Constitution is the supreme law that establishes the framework of government.', difficulty: 'EASY' },
      { question: 'Which article typically deals with fundamental rights?', optionA: 'Article 1', optionB: 'Article 2', optionC: 'Part III (Articles 12-35)', optionD: 'Part IV', correctOption: 'C', explanation: 'Fundamental Rights are usually enshrined in a dedicated section of the constitution.', difficulty: 'MEDIUM' },
      { question: 'What does "Habeas Corpus" mean?', optionA: 'Show the body', optionB: 'You have the body', optionC: 'Protection against illegal detention', optionD: 'Both B and C', correctOption: 'D', explanation: 'Habeas Corpus protects against unlawful detention by requiring the detainer to justify it.', difficulty: 'MEDIUM' },
      { question: 'What is judicial review?', optionA: 'Reviewing court cases', optionB: 'Power of courts to invalidate unconstitutional laws', optionC: 'Reviewing judge performance', optionD: 'Appealing a verdict', correctOption: 'B', explanation: 'Judicial review is the power of courts to examine and invalidate laws that violate the constitution.', difficulty: 'MEDIUM' },
      { question: 'Which branch of government interprets laws?', optionA: 'Executive', optionB: 'Legislative', optionC: 'Judiciary', optionD: 'Military', correctOption: 'C', explanation: 'The judiciary interprets and applies the law through court decisions.', difficulty: 'EASY' },
      { question: 'What is a "Bill of Rights"?', optionA: 'A financial document', optionB: 'A list of fundamental rights protected by law', optionC: 'A legislative proposal', optionD: 'A tax document', correctOption: 'B', explanation: 'A Bill of Rights enumerates individual rights protected from government infringement.', difficulty: 'EASY' },
      { question: 'What is the principle of "Separation of Powers"?', optionA: 'All power to one branch', optionB: 'Dividing government into legislative, executive, and judicial branches', optionC: 'State and federal division', optionD: 'Military and civilian division', correctOption: 'B', explanation: 'Separation of powers divides government authority among three branches to prevent tyranny.', difficulty: 'MEDIUM' },
      { question: 'What does "Due Process" mean?', optionA: 'Fast trial', optionB: 'Fair treatment through judicial system', optionC: 'Free legal aid', optionD: 'Appeal process', correctOption: 'B', explanation: 'Due process ensures fair treatment under the law and protects individual rights.', difficulty: 'MEDIUM' },
      { question: 'What is an amendment to a constitution?', optionA: 'A new law', optionB: 'A formal change to the constitution', optionC: 'A court ruling', optionD: 'An executive order', correctOption: 'B', explanation: 'An amendment is a formal modification or addition to the constitution.', difficulty: 'EASY' },
      { question: 'Which type of law governs relationships between individuals?', optionA: 'Public law', optionB: 'Private/Civil law', optionC: 'Criminal law', optionD: 'International law', correctOption: 'B', explanation: 'Private/civil law governs disputes between private parties.', difficulty: 'MEDIUM' },
    ],
  },
  {
    name: 'Criminal Law',
    department: 'LLB',
    icon: '🔒',
    difficulty: 'MEDIUM',
    description: 'Crimes, defenses, procedures, and the Indian Penal Code',
    questions: [
      { question: 'What is the basic definition of a crime?', optionA: 'Any act that is immoral', optionB: 'An act or omission prohibited by law and punishable by the state', optionC: 'A civil wrong', optionD: 'A breach of contract', correctOption: 'B', explanation: 'A crime (offense) is an act or omission that violates criminal law and is punishable by the state through fines, imprisonment, or other sanctions.', difficulty: 'EASY' },
      { question: 'Under the Indian Penal Code, what is "mens rea"?', optionA: 'Physical act of committing a crime', optionB: 'Guilty mind or criminal intention', optionC: 'The punishment prescribed', optionD: 'The victim of the crime', correctOption: 'B', explanation: 'Mens rea (guilty mind) refers to the mental element or intention to commit a crime. It is a fundamental principle in criminal law.', difficulty: 'MEDIUM' },
      { question: 'What is the difference between "theft" and "robbery" under the IPC?', optionA: 'There is no difference', optionB: 'Robbery involves force or threat of force; theft does not', optionC: 'Theft involves more money than robbery', optionD: 'Robbery is a civil matter; theft is criminal', correctOption: 'B', explanation: 'Theft (Section 378 IPC) is taking property dishonestly. Robbery (Section 390 IPC) is theft committed with force, violence, or threat.', difficulty: 'MEDIUM' },
      { question: 'Which Section of the IPC deals with murder?', optionA: 'Section 299', optionB: 'Section 300', optionC: 'Section 302', optionD: 'Section 304', correctOption: 'C', explanation: 'Section 302 of the IPC prescribes punishment for murder. Section 300 defines murder, and Section 299 defines culpable homicide.', difficulty: 'HARD' },
      { question: 'What is "bail" in criminal procedure?', optionA: 'A final judgment', optionB: 'Temporary release of an accused person pending trial, with conditions', optionC: 'A type of punishment', optionD: 'A guilty plea', correctOption: 'B', explanation: 'Bail allows an accused person to be released from custody while awaiting trial, usually on the condition of posting a bond or money.', difficulty: 'EASY' },
      { question: 'What is self-defense as a legal defense?', optionA: 'Taking revenge on the attacker', optionB: 'Using reasonable force to protect oneself from imminent harm', optionC: 'Preemptively attacking a suspect', optionD: 'A justification for any violent act', correctOption: 'B', explanation: 'Self-defense (private defense under IPC Sections 96-106) justifies using reasonable force to protect oneself, others, or property from imminent danger.', difficulty: 'MEDIUM' },
      { question: 'What is "sedition" under criminal law?', optionA: 'Violent protest', optionB: 'Speech or conduct inciting rebellion against the government', optionC: 'Peaceful criticism of the government', optionD: 'Treason against a foreign state', correctOption: 'B', explanation: 'Sedition involves acts or speech intended to incite rebellion or hatred against the established government authority.', difficulty: 'MEDIUM' },
      { question: 'What is the principle of "beyond reasonable doubt"?', optionA: 'A low standard of proof', optionB: 'The prosecution must prove guilt to a high degree of certainty', optionC: 'The defense must prove innocence', optionD: 'No evidence is required', correctOption: 'B', explanation: 'In criminal law, the prosecution must prove the defendant\'s guilt "beyond a reasonable doubt," the highest standard of proof.', difficulty: 'MEDIUM' },
      { question: 'What is the difference between "culpable homicide" and "murder"?', optionA: 'They are the same thing', optionB: 'All murder is culpable homicide, but not all culpable homicide is murder', optionC: 'Culpable homicide is more serious than murder', optionD: 'Only murder requires mens rea', correctOption: 'B', explanation: 'Under IPC, culpable homicide (Sec 299) is the broader category. Murder (Sec 300) is culpable homicide with specific aggravating conditions like premeditation.', difficulty: 'HARD' },
      { question: 'What is an FIR (First Information Report)?', optionA: 'A court judgment', optionB: 'The initial report filed with police about a cognizable offense', optionC: 'A bail application', optionD: 'A charge sheet', correctOption: 'B', explanation: 'An FIR is the first information about a cognizable (serious) criminal offense given to the police, which sets the criminal justice process in motion.', difficulty: 'EASY' },
    ],
  },
  {
    name: 'Contract Law',
    department: 'LLB',
    icon: '📝',
    difficulty: 'MEDIUM',
    description: 'Offer, acceptance, consideration, breach, and remedies',
    questions: [
      { question: 'What are the essential elements of a valid contract?', optionA: 'Offer and acceptance only', optionB: 'Offer, acceptance, consideration, intention, capacity, and legality', optionC: 'Written document and signatures', optionD: 'Payment and delivery', correctOption: 'B', explanation: 'A valid contract requires: offer, acceptance, consideration, intention to create legal relations, capacity to contract, and lawful object.', difficulty: 'MEDIUM' },
      { question: 'What is "consideration" in contract law?', optionA: 'Being considerate to the other party', optionB: 'Something of value exchanged between parties to a contract', optionC: 'A legal opinion', optionD: 'The time taken to review a contract', correctOption: 'B', explanation: 'Consideration is what each party gives up or promises in exchange for what the other party gives or promises. Without consideration, a contract is generally not enforceable.', difficulty: 'EASY' },
      { question: 'What is an "invitation to treat" vs an "offer"?', optionA: 'They are the same thing', optionB: 'An invitation to treat invites offers; it is not itself a binding offer', optionC: 'An invitation to treat is legally binding', optionD: 'An offer is not legally binding', correctOption: 'B', explanation: 'An invitation to treat (e.g., a shop display or advertisement) invites others to make offers. It is not a binding offer itself.', difficulty: 'MEDIUM' },
      { question: 'What is a "void contract"?', optionA: 'A contract with a minor typo', optionB: 'A contract that is not enforceable by law from the beginning', optionC: 'A contract that can be cancelled by one party', optionD: 'A contract that has been fulfilled', correctOption: 'B', explanation: 'A void contract has no legal effect from inception — it is as if the contract never existed (e.g., agreements with minors, illegal contracts).', difficulty: 'EASY' },
      { question: 'What is the doctrine of "frustration of contract"?', optionA: 'A party is unhappy with the contract', optionB: 'A contract becomes impossible to perform due to unforeseen events', optionC: 'The contract was signed under pressure', optionD: 'One party breaches the contract', correctOption: 'B', explanation: 'Frustration occurs when an unforeseen event makes contract performance impossible, illegal, or radically different from what was agreed, discharging both parties.', difficulty: 'HARD' },
      { question: 'What is "specific performance" as a remedy for breach?', optionA: 'Paying monetary damages', optionB: 'A court order compelling the breaching party to fulfill their contractual obligations', optionC: 'Cancelling the contract', optionD: 'Rescinding the agreement', correctOption: 'B', explanation: 'Specific performance is an equitable remedy where the court orders the party in breach to carry out the contract as agreed, rather than just paying damages.', difficulty: 'HARD' },
      { question: 'When can a contract be terminated?', optionA: 'Only by mutual agreement', optionB: 'By performance, breach, frustration, agreement, or operation of law', optionC: 'Only by a court order', optionD: 'Only when one party dies', correctOption: 'B', explanation: 'A contract can be discharged by: performance, breach, frustration/agreement, lapse of time, operation of law, or impossibility.', difficulty: 'MEDIUM' },
      { question: 'What is a "voidable contract"?', optionA: 'A contract that is always valid', optionB: 'A contract that can be affirmed or rejected by one party (e.g., due to undue influence)', optionC: 'A contract with no consideration', optionD: 'A contract for illegal purposes', correctOption: 'B', explanation: 'A voidable contract is valid and binding unless one party chooses to reject it. Common grounds include misrepresentation, undue influence, or coercion.', difficulty: 'MEDIUM' },
      { question: 'What is "misrepresentation" in contract law?', optionA: 'Accidental error', optionB: 'A false statement of fact that induces the other party to enter the contract', optionC: 'An opinion about future events', optionD: 'A promise to do something', correctOption: 'B', explanation: 'Misrepresentation is a false statement of material fact made by one party, which the other relies on when entering the contract. It can make the contract voidable.', difficulty: 'MEDIUM' },
      { question: 'What is the Indian Contract Act, 1872 primarily based on?', optionA: 'American contract law', optionB: 'English common law principles of contract', optionC: 'Islamic law principles', optionD: 'Customary law only', correctOption: 'B', explanation: 'The Indian Contract Act, 1872 is primarily based on English common law principles of contract, adapted to Indian conditions.', difficulty: 'EASY' },
    ],
  },
  {
    name: 'International Law',
    department: 'LLB',
    icon: '🌍',
    difficulty: 'MEDIUM',
    description: 'Treaties, United Nations, human rights, and state sovereignty',
    questions: [
      { question: 'What is international law?', optionA: 'Law that governs domestic disputes', optionB: 'A set of rules and principles governing relations between states and international organizations', optionC: 'Laws passed by a single country', optionD: 'Trade regulations within a country', correctOption: 'B', explanation: 'International law consists of treaties, customs, and principles that govern the relationships between sovereign states and international organizations.', difficulty: 'EASY' },
      { question: 'When was the United Nations founded?', optionA: '1918', optionB: '1945', optionC: '1950', optionD: '1939', correctOption: 'B', explanation: 'The United Nations was founded on October 24, 1945, after the end of World War II, to promote international cooperation and peace.', difficulty: 'EASY' },
      { question: 'What is the principle of state sovereignty in international law?', optionA: 'A state can do anything it wants', optionB: 'A state has supreme authority within its territorial boundaries', optionC: 'States must obey all other nations', optionD: 'Only large nations have sovereignty', correctOption: 'B', explanation: 'State sovereignty means each nation-state has exclusive authority over its territory and domestic affairs, free from external interference.', difficulty: 'MEDIUM' },
      { question: 'What is a treaty in international law?', optionA: 'An informal agreement', optionB: 'A formally concluded and ratified agreement between states', optionC: 'A domestic law', optionD: 'A UN resolution', correctOption: 'B', explanation: 'A treaty is a legally binding international agreement concluded between states in written form and governed by international law (Vienna Convention on the Law of Treaties, 1969).', difficulty: 'MEDIUM' },
      { question: 'Which document is the foundation of international human rights law?', optionA: 'The Geneva Convention', optionB: 'The Universal Declaration of Human Rights (UDHR)', optionC: 'The Treaty of Westphalia', optionD: 'The NATO Charter', correctOption: 'B', explanation: 'The UDHR, adopted by the UN General Assembly in 1948, establishes fundamental human rights to be universally protected.', difficulty: 'EASY' },
      { question: 'What is the International Court of Justice (ICJ)?', optionA: 'A domestic court', optionB: 'The principal judicial organ of the United Nations', optionC: 'A human rights tribunal', optionD: 'A trade dispute body', correctOption: 'B', explanation: 'The ICJ, located in The Hague, is the principal judicial organ of the UN. It settles legal disputes submitted by states and gives advisory opinions.', difficulty: 'MEDIUM' },
      { question: 'What is "jus cogens" in international law?', optionA: 'Regular treaty obligations', optionB: 'Peremptory norms from which no derogation is permitted', optionC: 'Customary international law', optionD: 'Soft law principles', correctOption: 'B', explanation: 'Jus cogens (compelling law) are fundamental principles of international law that cannot be overridden by treaty or custom, such as the prohibition of genocide and slavery.', difficulty: 'HARD' },
      { question: 'What is the doctrine of "pacta sunt servanda"?', optionA: 'Treaties can be broken at will', optionB: 'Every treaty in force is binding upon the parties and must be performed in good faith', optionC: 'Only written treaties are valid', optionD: 'Treaties expire after 10 years', correctOption: 'B', explanation: 'Pacta sunt servanda (agreements must be kept) is a foundational principle of treaty law under Article 26 of the Vienna Convention.', difficulty: 'HARD' },
      { question: 'What are the sources of international law as per Article 38 of the ICJ Statute?', optionA: 'Only treaties', optionB: 'Treaties, customs, general principles, and judicial decisions/scholarship', optionC: 'Only UN resolutions', optionD: 'Only customary practices', correctOption: 'B', explanation: 'Article 38 lists: international conventions (treaties), international custom, general principles of law, and judicial decisions/writings as subsidiary sources.', difficulty: 'HARD' },
      { question: 'What does "diplomatic immunity" mean?', optionA: 'Diplomats can commit any crime without consequences', optionB: 'Diplomats are protected from prosecution in the host country for official acts', optionC: 'Diplomats do not need visas', optionD: 'Diplomats are above all domestic laws', correctOption: 'B', explanation: 'Diplomatic immunity protects diplomats from legal jurisdiction in the host country for their official acts, ensuring they can perform duties without interference.', difficulty: 'MEDIUM' },
    ],
  },
  {
    name: 'Corporate Law',
    department: 'LLB',
    icon: '🏢',
    difficulty: 'MEDIUM',
    description: 'Company formation, governance, compliance, and corporate regulation',
    questions: [
      { question: 'What is a "limited liability company"?', optionA: 'A company with no debts', optionB: 'A company where shareholders\' liability is limited to their share capital', optionC: 'A government-owned company', optionD: 'A non-profit organization', correctOption: 'B', explanation: 'In a limited liability company, shareholders are not personally liable for the company\'s debts beyond their investment in shares.', difficulty: 'EASY' },
      { question: 'What is the Memorandum of Association (MoA)?', optionA: 'A list of shareholders', optionB: 'The founding document defining the company\'s scope, objectives, and powers', optionC: 'A financial statement', optionD: 'An employee handbook', correctOption: 'B', explanation: 'The MoA is the charter of the company that defines its relationship with shareholders and the scope of its operations beyond which it cannot act.', difficulty: 'MEDIUM' },
      { question: 'Under the Indian Companies Act, 2013, what is the minimum number of members for a private company?', optionA: '1', optionB: '2', optionC: '7', optionD: '50', correctOption: 'B', explanation: 'A private company requires a minimum of 2 members and maximum of 200 members, as per Section 2(68) of the Companies Act, 2013.', difficulty: 'MEDIUM' },
      { question: 'What is "corporate governance"?', optionA: 'Government control of private companies', optionB: 'The system of rules, practices, and processes by which a company is directed and controlled', optionC: 'A tax on corporate profits', optionD: 'A type of insurance', correctOption: 'B', explanation: 'Corporate governance involves the mechanisms, processes, and relations by which corporations are controlled and directed, balancing stakeholder interests.', difficulty: 'MEDIUM' },
      { question: 'What is insider trading?', optionA: 'Trading goods between countries', optionB: 'Trading securities based on material non-public information', optionC: 'Buying and selling within the company', optionD: 'A legal practice in stock markets', correctOption: 'B', explanation: 'Insider trading is the illegal practice of trading stocks or securities based on confidential, material information not available to the public.', difficulty: 'EASY' },
      { question: 'What is the role of an independent director on a board?', optionA: 'To manage daily operations', optionB: 'To provide unbiased oversight and protect shareholder interests', optionC: 'To represent the government', optionD: 'To handle legal disputes', correctOption: 'B', explanation: 'Independent directors are not involved in the day-to-day operations and provide objective judgment on corporate matters, free from conflicts of interest.', difficulty: 'MEDIUM' },
      { question: 'What is a "Shareholders\' Agreement"?', optionA: 'An agreement between a company and its employees', optionB: 'A contract between shareholders governing their rights and obligations', optionC: 'A loan agreement', optionD: 'A government regulation', correctOption: 'B', explanation: 'A Shareholders\' Agreement is a private contract between some or all shareholders that sets out their rights, obligations, and dispute resolution mechanisms.', difficulty: 'HARD' },
      { question: 'What is "winding up" of a company?', optionA: 'Starting a new company', optionB: 'The process of closing a company and distributing its assets', optionC: 'Reorganizing a company\'s structure', optionD: 'Merging two companies', correctOption: 'B', explanation: 'Winding up (liquidation) is the process of dissolving a company by selling its assets, paying creditors, and distributing remaining assets to shareholders.', difficulty: 'EASY' },
      { question: 'What is the difference between a public company and a private company?', optionA: 'There is no difference', optionB: 'A public company can offer shares to the public; a private company cannot', optionC: 'A private company is larger', optionD: 'A public company does not have shareholders', correctOption: 'B', explanation: 'A public company can raise funds from the public by offering shares (requires minimum 7 members), while a private company cannot (requires minimum 2 members).', difficulty: 'MEDIUM' },
      { question: 'What is "corporate social responsibility" (CSR) under the Companies Act?', optionA: 'A voluntary charity', optionB: 'Mandatory spending on social welfare by companies meeting certain financial thresholds', optionC: 'A tax benefit scheme', optionD: 'A marketing strategy', correctOption: 'B', explanation: 'Under Section 135 of the Companies Act, 2013, companies meeting specified financial criteria must spend at least 2% of average net profits on CSR activities.', difficulty: 'HARD' },
    ],
  },

  // ============================================================
  // EEE DEPARTMENT
  // ============================================================
  {
    name: 'Circuit Analysis',
    department: 'EEE',
    icon: '⚡',
    difficulty: 'MEDIUM',
    description: 'Fundamentals of electrical circuits and electronics',
    questions: [
      { question: "What is Ohm's Law?", optionA: 'V = IR', optionB: 'P = IV', optionC: 'V = LC', optionD: 'I = VR', correctOption: 'A', explanation: "Ohm's Law states that voltage equals current times resistance (V = IR).", difficulty: 'EASY' },
      { question: 'What is the unit of resistance?', optionA: 'Volt', optionB: 'Ampere', optionC: 'Ohm (Ω)', optionD: 'Watt', correctOption: 'C', explanation: 'Resistance is measured in Ohms (Ω).', difficulty: 'EASY' },
      { question: 'In a series circuit, what remains constant?', optionA: 'Voltage', optionB: 'Current', optionC: 'Resistance', optionD: 'Power', correctOption: 'B', explanation: 'In a series circuit, current is the same through all components.', difficulty: 'MEDIUM' },
      { question: "What is Kirchhoff's Current Law (KCL)?", optionA: 'Sum of voltages around a loop is zero', optionB: 'Sum of currents entering a node equals sum leaving', optionC: 'Total resistance is sum of resistances', optionD: 'Current is proportional to voltage', correctOption: 'B', explanation: 'KCL states that the algebraic sum of currents at any node is zero.', difficulty: 'MEDIUM' },
      { question: 'What is a capacitor?', optionA: 'A device that stores charge', optionB: 'A device that amplifies signals', optionC: 'A type of resistor', optionD: 'A power source', correctOption: 'A', explanation: 'A capacitor stores electric charge and energy in an electric field.', difficulty: 'EASY' },
      { question: 'What is the resonant frequency of an LC circuit?', optionA: 'f = 1/(2π√LC)', optionB: 'f = LC', optionC: 'f = 2πLC', optionD: 'f = 1/LC', correctOption: 'A', explanation: 'The resonant frequency formula is f = 1/(2π√LC).', difficulty: 'HARD' },
      { question: 'What does a diode do?', optionA: 'Stores energy', optionB: 'Amplifies signals', optionC: 'Allows current in one direction', optionD: 'Measures voltage', correctOption: 'C', explanation: 'A diode allows current to flow in only one direction (forward bias).', difficulty: 'EASY' },
      { question: 'What is AC current?', optionA: 'Always positive', optionB: 'Alternates direction periodically', optionC: 'Constant current', optionD: 'Direct current', correctOption: 'B', explanation: 'AC (Alternating Current) periodically reverses direction.', difficulty: 'EASY' },
      { question: 'What is power in an electrical circuit?', optionA: 'P = V + I', optionB: 'P = V × I', optionC: 'P = V / I', optionD: 'P = V - I', correctOption: 'B', explanation: 'Electrical power is the product of voltage and current (P = VI).', difficulty: 'EASY' },
      { question: 'What is a transformer?', optionA: 'Converts AC to DC', optionB: 'Changes voltage levels using electromagnetic induction', optionC: 'Stores electrical energy', optionD: 'Amplifies current', correctOption: 'B', explanation: 'A transformer changes voltage levels through electromagnetic induction between coils.', difficulty: 'MEDIUM' },
    ],
  },
  {
    name: 'Digital Electronics',
    department: 'EEE',
    icon: '🔢',
    difficulty: 'MEDIUM',
    description: 'Logic gates, flip-flops, counters, ADC/DAC, and digital systems',
    questions: [
      { question: 'What is the output of an AND gate when both inputs are 1?', optionA: '0', optionB: '1', optionC: 'Undefined', optionD: 'Depends on the gate', correctOption: 'B', explanation: 'An AND gate outputs 1 only when all inputs are 1. 1 AND 1 = 1.', difficulty: 'EASY' },
      { question: 'How many inputs does a NOT gate have?', optionA: '0', optionB: '1', optionC: '2', optionD: '3', correctOption: 'B', explanation: 'A NOT gate (inverter) has a single input and produces the complement (opposite) of the input.', difficulty: 'EASY' },
      { question: 'What is the universal gate?', optionA: 'AND gate', optionB: 'OR gate', optionC: 'NAND gate', optionD: 'XOR gate', correctOption: 'C', explanation: 'NAND and NOR are universal gates — any Boolean function can be implemented using only NAND or only NOR gates.', difficulty: 'MEDIUM' },
      { question: 'What is a flip-flop in digital electronics?', optionA: 'A type of logic gate', optionB: 'A sequential circuit that stores one bit of data', optionC: 'A combinational circuit', optionD: 'A type of counter', correctOption: 'B', explanation: 'A flip-flop is a bistable multivibrator — a circuit that has two stable states and can store one bit of binary information.', difficulty: 'MEDIUM' },
      { question: 'What is the hexadecimal equivalent of binary 1010?', optionA: 'A', optionB: 'B', optionC: 'C', optionD: '10', correctOption: 'A', explanation: 'Binary 1010 = decimal 10 = hexadecimal A.', difficulty: 'EASY' },
      { question: 'What is a multiplexer (MUX)?', optionA: 'A device that splits one signal into many', optionB: 'A device that selects one input from many and forwards it to a single output', optionC: 'A type of memory', optionD: 'A flip-flop variant', correctOption: 'B', explanation: 'A multiplexer is a combinational circuit that selects one of several input lines and directs it to a single output line based on select signals.', difficulty: 'MEDIUM' },
      { question: 'What is the purpose of an ADC?', optionA: 'To convert digital signals to analog', optionB: 'To convert analog signals to digital', optionC: 'To amplify signals', optionD: 'To filter noise', correctOption: 'B', explanation: 'An Analog-to-Digital Converter (ADC) converts continuous analog signals into discrete digital numbers for processing by digital systems.', difficulty: 'EASY' },
      { question: 'How many flip-flops are needed for a mod-16 counter?', optionA: '2', optionB: '3', optionC: '4', optionD: '5', correctOption: 'C', explanation: 'A mod-16 counter counts from 0 to 15 (16 states). Since n flip-flops can represent 2^n states, we need 4 flip-flops (2^4 = 16).', difficulty: 'MEDIUM' },
      { question: 'What is De Morgan\'s Theorem?', optionA: 'A + B = AB', optionB: '(AB)\' = A\' + B\' and (A + B)\' = A\'B\'', optionC: 'A + A\' = 0', optionD: 'AA\' = 1', correctOption: 'B', explanation: "De Morgan's Theorem states that the complement of a product equals the sum of complements, and the complement of a sum equals the product of complements.", difficulty: 'HARD' },
      { question: 'What is a shift register?', optionA: 'A register that performs arithmetic operations', optionB: 'A sequential circuit that shifts stored bits left or right', optionC: 'A type of counter', optionD: 'A combinational logic circuit', correctOption: 'B', explanation: 'A shift register is a cascade of flip-flops where the output of one connects to the input of the next, enabling bit-by-bit data shifting.', difficulty: 'HARD' },
    ],
  },
  {
    name: 'Power Systems',
    department: 'EEE',
    icon: '🔌',
    difficulty: 'MEDIUM',
    description: 'Generation, transmission, distribution, transformers, and power plants',
    questions: [
      { question: 'What is the standard frequency of AC power supply in India?', optionA: '50 Hz', optionB: '60 Hz', optionC: '25 Hz', optionD: '100 Hz', correctOption: 'A', explanation: 'The standard frequency of AC power supply in India and most of the world (except North America) is 50 Hz.', difficulty: 'EASY' },
      { question: 'What is the purpose of a step-up transformer at a power generating station?', optionA: 'To increase current', optionB: 'To increase voltage for efficient long-distance transmission', optionC: 'To convert AC to DC', optionD: 'To regulate frequency', correctOption: 'B', explanation: 'Step-up transformers increase voltage at the generating station to reduce transmission losses (I²R losses) over long distances.', difficulty: 'MEDIUM' },
      { question: 'Which type of power plant uses uranium as fuel?', optionA: 'Thermal power plant', optionB: 'Nuclear power plant', optionC: 'Hydroelectric power plant', optionD: 'Solar power plant', correctOption: 'B', explanation: 'Nuclear power plants use uranium (or plutonium) as fuel for nuclear fission, which generates heat to produce steam and drive turbines.', difficulty: 'EASY' },
      { question: 'What is the main disadvantage of high-voltage DC (HVDC) transmission?', optionA: 'High energy losses', optionB: 'Expensive converter stations at both ends', optionC: 'Cannot transmit over long distances', optionD: 'Limited power capacity', correctOption: 'B', explanation: 'HVDC transmission has lower line losses than HVAC but requires expensive AC-DC converter stations at both terminals.', difficulty: 'HARD' },
      { question: 'What is a "bus bar" in a power system?', optionA: 'A transportation vehicle', optionB: 'A conductor used to collect and distribute electric power', optionC: 'A type of circuit breaker', optionD: 'A grounding device', correctOption: 'B', explanation: 'A bus bar is a thick copper or aluminum strip/bar that collects electric power from incoming feeders and distributes it to outgoing feeders.', difficulty: 'MEDIUM' },
      { question: 'What is the "load factor" in power systems?', optionA: 'The ratio of peak load to average load', optionB: 'The ratio of average load to peak (maximum) load over a period', optionC: 'The total energy consumed', optionD: 'The maximum voltage variation', correctOption: 'B', explanation: 'Load factor = Average Load / Maximum Demand. A higher load factor indicates better utilization of the power system.', difficulty: 'HARD' },
      { question: 'What is corona discharge in transmission lines?', optionA: 'A type of power surge', optionB: 'Ionization of air around conductors causing power loss and noise', optionC: 'A protective device', optionD: 'A grounding technique', correctOption: 'B', explanation: 'Corona discharge occurs when the voltage gradient at the conductor surface exceeds the dielectric strength of air, causing ionization, power loss, and radio interference.', difficulty: 'MEDIUM' },
      { question: 'Which material is most commonly used for overhead transmission line conductors?', optionA: 'Copper', optionB: 'Aluminum (ACSR)', optionC: 'Steel', optionD: 'Silver', correctOption: 'B', explanation: 'ACSR (Aluminum Conductor Steel Reinforced) is the most commonly used overhead conductor, combining aluminum\'s conductivity with steel\'s strength.', difficulty: 'EASY' },
      { question: 'What is the purpose of a circuit breaker in a power system?', optionA: 'To regulate voltage', optionB: 'To automatically interrupt fault currents and protect equipment', optionC: 'To measure power consumption', optionD: 'To step up voltage', correctOption: 'B', explanation: 'A circuit breaker automatically detects fault conditions (overcurrent, short circuit) and interrupts the flow of current to protect equipment and prevent fires.', difficulty: 'EASY' },
      { question: 'What is a "smart grid"?', optionA: 'A grid with more wires', optionB: 'An electricity network using digital technology for monitoring and management', optionC: 'A grid powered only by renewable energy', optionD: 'A grid without transmission losses', correctOption: 'B', explanation: 'A smart grid uses digital communication, sensors, and automation to monitor, control, and optimize power generation, transmission, and distribution.', difficulty: 'MEDIUM' },
    ],
  },
  {
    name: 'Signals & Systems',
    department: 'EEE',
    icon: '📈',
    difficulty: 'MEDIUM',
    description: 'Fourier, Laplace, Z-transform, sampling, and signal analysis',
    questions: [
      { question: 'What is a periodic signal?', optionA: 'A signal that never repeats', optionB: 'A signal that repeats its pattern at regular time intervals', optionC: 'A signal with zero amplitude', optionD: 'A signal with only one frequency', correctOption: 'B', explanation: 'A periodic signal satisfies x(t) = x(t + T) for all t, where T is the period of repetition.', difficulty: 'EASY' },
      { question: 'What is the Fourier Transform used for?', optionA: 'Amplifying signals', optionB: 'Decomposing a signal into its frequency components', optionC: 'Filtering noise', optionD: 'Sampling signals', correctOption: 'B', explanation: 'The Fourier Transform converts a time-domain signal into its frequency-domain representation, showing which frequencies are present in the signal.', difficulty: 'MEDIUM' },
      { question: 'According to the Nyquist theorem, what is the minimum sampling rate to avoid aliasing?', optionA: 'Equal to the signal frequency', optionB: 'At least twice the maximum frequency component', optionC: 'At least ten times the signal frequency', optionD: 'Half the signal frequency', correctOption: 'B', explanation: 'The Nyquist-Shannon sampling theorem states that a signal must be sampled at least at 2× its highest frequency to perfectly reconstruct it without aliasing.', difficulty: 'MEDIUM' },
      { question: 'What is the Laplace Transform of a unit step function u(t)?', optionA: '1/s', optionB: 's', optionC: '1/s²', optionD: '1', correctOption: 'A', explanation: 'The Laplace Transform of the unit step function u(t) is L{u(t)} = 1/s for Re(s) > 0.', difficulty: 'MEDIUM' },
      { question: 'What is Linearity in the context of systems?', optionA: 'The output has a straight line graph', optionB: 'The system satisfies superposition and homogeneity (scaling) properties', optionC: 'The system has no distortion', optionD: 'The system only accepts one input', correctOption: 'B', explanation: 'A system is linear if it satisfies both superposition (f(x₁+x₂) = f(x₁)+f(x₂)) and homogeneity (f(ax) = a·f(x)).', difficulty: 'EASY' },
      { question: 'What is the Z-Transform primarily used for?', optionA: 'Analog signal analysis', optionB: 'Analysis of discrete-time signals and systems', optionC: 'Power system analysis', optionD: 'Circuit analysis', correctOption: 'B', explanation: 'The Z-Transform is the discrete-time counterpart of the Laplace Transform, used for analyzing digital/discrete-time signals and systems.', difficulty: 'MEDIUM' },
      { question: 'What is "aliasing" in signal processing?', optionA: 'Signal amplification error', optionB: 'Distortion caused by under-sampling, where high frequencies appear as lower frequencies', optionC: 'A type of filter', optionD: 'A modulation technique', correctOption: 'B', explanation: 'Aliasing occurs when a signal is sampled below the Nyquist rate, causing different frequency components to become indistinguishable.', difficulty: 'MEDIUM' },
      { question: 'What is a causal system?', optionA: 'A system that works in reverse', optionB: 'A system whose output depends only on present and past inputs', optionC: 'A system with zero delay', optionD: 'A system that predicts the future', correctOption: 'B', explanation: 'A causal system\'s output at any time depends only on present and past input values, never on future inputs.', difficulty: 'HARD' },
      { question: 'What is convolution in signals and systems?', optionA: 'A type of signal modulation', optionB: 'A mathematical operation that combines two signals to produce a third', optionC: 'A filtering technique', optionD: 'A sampling method', correctOption: 'B', explanation: 'Convolution expresses the output of an LTI (Linear Time-Invariant) system as the integral/sum of the input weighted by the system\'s impulse response.', difficulty: 'HARD' },
      { question: 'What is the relationship between Fourier series and Fourier Transform?', optionA: 'They are completely different', optionB: 'Fourier series is for periodic signals; Fourier Transform extends this to aperiodic signals', optionC: 'Fourier Transform is only for discrete signals', optionD: 'Fourier series is more powerful', correctOption: 'B', explanation: 'Fourier series represents periodic signals as sums of sinusoids. Fourier Transform generalizes this to aperiodic signals by letting the period approach infinity.', difficulty: 'HARD' },
    ],
  },
  {
    name: 'Control Systems',
    department: 'EEE',
    icon: '🎛️',
    difficulty: 'MEDIUM',
    description: 'Feedback, stability, PID controllers, and transfer functions',
    questions: [
      { question: 'What is an open-loop control system?', optionA: 'A system with feedback', optionB: 'A system where the output has no effect on the control action', optionC: 'A system that is always unstable', optionD: 'A digital control system', correctOption: 'B', explanation: 'In an open-loop system, the control action is independent of the desired output. There is no feedback from the output to the input.', difficulty: 'EASY' },
      { question: 'What is the primary advantage of a closed-loop (feedback) control system?', optionA: 'Lower cost', optionB: 'Greater accuracy and reduced sensitivity to disturbances', optionC: 'Simpler design', optionD: 'No maintenance needed', correctOption: 'B', explanation: 'Closed-loop systems use feedback to compare actual output with desired output, automatically correcting errors and reducing the impact of disturbances.', difficulty: 'EASY' },
      { question: 'What does a PID controller stand for?', optionA: 'Primary Input Device', optionB: 'Proportional, Integral, Derivative', optionC: 'Power Input Distribution', optionD: 'Programmable Intelligent Device', correctOption: 'B', explanation: 'PID stands for Proportional-Integral-Derivative. It combines three control actions to minimize error between desired and actual output.', difficulty: 'EASY' },
      { question: 'What is the transfer function of a system?', optionA: 'The ratio of force to displacement', optionB: 'The ratio of Laplace transform of output to input (with zero initial conditions)', optionC: 'The power consumed by the system', optionD: 'The time response of the system', correctOption: 'B', explanation: 'The transfer function G(s) = C(s)/R(s) is the Laplace-domain ratio of output to input, assuming zero initial conditions. It characterizes the system.', difficulty: 'MEDIUM' },
      { question: 'A system is "marginally stable" if its poles lie where?', optionA: 'Left half of the s-plane', optionB: 'Right half of the s-plane', optionC: 'On the imaginary axis (jω axis)', optionD: 'At the origin only', correctOption: 'C', explanation: 'Marginally stable systems have poles on the imaginary axis, resulting in sustained oscillations. Poles in the left half mean stable; in the right half means unstable.', difficulty: 'HARD' },
      { question: 'What is the "steady-state error" of a control system?', optionA: 'The error during transient response', optionB: 'The difference between desired output and actual output after transients have died out', optionC: 'The maximum overshoot', optionD: 'The settling time', correctOption: 'B', explanation: 'Steady-state error is the remaining difference between the desired final value and the actual output value after the transient response has settled.', difficulty: 'MEDIUM' },
      { question: 'What is the Routh-Hurwitz criterion used for?', optionA: 'To design controllers', optionB: 'To determine stability without calculating pole locations', optionC: 'To find the transfer function', optionD: 'To measure frequency response', correctOption: 'B', explanation: 'The Routh-Hurwitz criterion is a mathematical method to determine how many roots of a characteristic equation lie in the right half-plane, indicating instability.', difficulty: 'HARD' },
      { question: 'What does "gain margin" indicate in a Bode plot?', optionA: 'The system bandwidth', optionB: 'The amount of gain increase required to make the system unstable', optionC: 'The phase difference between input and output', optionD: 'The system time delay', correctOption: 'B', explanation: 'Gain margin is the amount (in dB) by which the system gain can be increased before the system reaches the verge of instability (phase crossover).', difficulty: 'HARD' },
      { question: 'In a PID controller, what does the "D" (Derivative) term do?', optionA: 'Eliminates steady-state error', optionB: 'Predicts future error based on rate of change, providing damping', optionC: 'Increases the response speed', optionD: 'Reduces the proportional gain', correctOption: 'B', explanation: 'The derivative term responds to the rate of change of error, providing a damping effect that reduces overshoot and improves transient response.', difficulty: 'MEDIUM' },
      { question: 'What is a "root locus" plot?', optionA: 'A plot of input vs output', optionB: 'A graphical representation of how closed-loop poles move as a parameter varies', optionC: 'A frequency response plot', optionD: 'A time-domain response curve', correctOption: 'B', explanation: 'The root locus shows the paths traced by the closed-loop poles of a system in the s-plane as a specific parameter (usually gain) varies from 0 to infinity.', difficulty: 'HARD' },
    ],
  },

  // ============================================================
  // BBA DEPARTMENT
  // ============================================================
  {
    name: 'Business Management',
    department: 'BBA',
    icon: '📊',
    difficulty: 'MEDIUM',
    description: 'Core business management and organizational concepts',
    questions: [
      { question: 'What is SWOT analysis?', optionA: 'Strengths, Weaknesses, Opportunities, Threats', optionB: 'Sales, Work, Output, Target', optionC: 'Strategy, Workflow, Operations, Tactics', optionD: 'Supply, Wages, Orders, Trade', correctOption: 'A', explanation: 'SWOT analysis evaluates internal strengths/weaknesses and external opportunities/threats.', difficulty: 'EASY' },
      { question: 'Who proposed the theory of Scientific Management?', optionA: 'Max Weber', optionB: 'Henri Fayol', optionC: 'Frederick Taylor', optionD: 'Peter Drucker', correctOption: 'C', explanation: 'Frederick Winslow Taylor is the father of Scientific Management.', difficulty: 'MEDIUM' },
      { question: 'What is ROI?', optionA: 'Rate of Interest', optionB: 'Return on Investment', optionC: 'Revenue of Income', optionD: 'Risk of Investment', correctOption: 'B', explanation: 'ROI measures the profitability of an investment relative to its cost.', difficulty: 'EASY' },
      { question: 'What is a "Balance Sheet"?', optionA: 'Income statement', optionB: 'Financial snapshot of assets, liabilities, and equity', optionC: 'Cash flow statement', optionD: 'Tax return', correctOption: 'B', explanation: 'A balance sheet shows assets = liabilities + equity at a point in time.', difficulty: 'MEDIUM' },
      { question: 'What is the marketing mix (4Ps)?', optionA: 'Price, Place, Product, Promotion', optionB: 'Plan, Process, People, Profit', optionC: 'Product, Performance, Price, Potential', optionD: 'Production, Profit, Price, Placement', correctOption: 'A', explanation: 'The 4Ps of marketing: Product, Price, Place, Promotion.', difficulty: 'EASY' },
      { question: 'What is "Break-even point"?', optionA: 'Maximum profit point', optionB: 'Where total revenue equals total cost', optionC: 'Point of no return', optionD: 'End of fiscal year', correctOption: 'B', explanation: 'Break-even is where revenue = costs, meaning no profit or loss.', difficulty: 'MEDIUM' },
      { question: 'What is "Supply Chain Management"?', optionA: 'Managing company supplies', optionB: 'End-to-end management of goods flow from raw materials to customer', optionC: 'Supplying chain stores', optionD: 'Managing vendor contracts', correctOption: 'B', explanation: 'SCM covers the entire flow of goods from supplier to manufacturer to consumer.', difficulty: 'MEDIUM' },
      { question: 'What is a "KPI"?', optionA: 'Key Performance Indicator', optionB: 'Key Product Index', optionC: 'Korean Process Improvement', optionD: 'Knowledge Process Integration', correctOption: 'A', explanation: 'KPIs are measurable values that demonstrate how effectively objectives are achieved.', difficulty: 'EASY' },
      { question: "What is Maslow's Hierarchy of Needs?", optionA: 'A financial theory', optionB: 'A motivation theory with 5 levels of human needs', optionC: 'A management style', optionD: 'A leadership model', correctOption: 'B', explanation: "Maslow's theory identifies 5 levels: physiological, safety, social, esteem, self-actualization.", difficulty: 'MEDIUM' },
      { question: 'What is "GDP"?', optionA: 'General Domestic Product', optionB: 'Gross Domestic Product', optionC: 'Global Development Plan', optionD: 'Government Debt Policy', correctOption: 'B', explanation: 'GDP is the total value of all goods and services produced within a country.', difficulty: 'EASY' },
    ],
  },
  {
    name: 'Mathematics',
    department: 'BBA',
    icon: '🔢',
    difficulty: 'MEDIUM',
    description: 'Business mathematics and quantitative methods',
    questions: [
      { question: 'What is the derivative of x²?', optionA: 'x', optionB: '2x', optionC: '2x²', optionD: 'x³', correctOption: 'B', explanation: 'Using the power rule: d/dx(x²) = 2x.', difficulty: 'EASY' },
      { question: 'What is the integral of 1/x?', optionA: 'x²', optionB: 'ln|x| + C', optionC: '1/x² + C', optionD: 'x + C', correctOption: 'B', explanation: 'The integral of 1/x is the natural logarithm: ln|x| + C.', difficulty: 'MEDIUM' },
      { question: 'What is the formula for compound interest?', optionA: 'A = P(1 + r/n)^(nt)', optionB: 'A = P × r × t', optionC: 'A = P + r', optionD: 'A = P/r', correctOption: 'A', explanation: 'Compound interest formula: A = P(1 + r/n)^(nt), where n is compounding frequency.', difficulty: 'MEDIUM' },
      { question: 'What is the mean of 4, 8, 12, 16?', optionA: '8', optionB: '10', optionC: '12', optionD: '16', correctOption: 'B', explanation: 'Mean = (4+8+12+16)/4 = 40/4 = 10.', difficulty: 'EASY' },
      { question: 'What is the determinant of a 2x2 matrix [a b; c d]?', optionA: 'a + d', optionB: 'ad - bc', optionC: 'ad + bc', optionD: 'ac - bd', correctOption: 'B', explanation: 'det([a b; c d]) = ad - bc.', difficulty: 'MEDIUM' },
      { question: 'What is log₁₀(1000)?', optionA: '2', optionB: '3', optionC: '4', optionD: '10', correctOption: 'B', explanation: 'log₁₀(1000) = 3 because 10³ = 1000.', difficulty: 'EASY' },
      { question: 'What is the probability of rolling a 6 on a fair die?', optionA: '1/2', optionB: '1/3', optionC: '1/6', optionD: '1/4', correctOption: 'C', explanation: 'A fair die has 6 equally likely outcomes, so P(6) = 1/6.', difficulty: 'EASY' },
      { question: 'What is the slope of the line y = 3x + 5?', optionA: '3', optionB: '5', optionC: '15', optionD: '8', correctOption: 'A', explanation: 'In y = mx + b form, m is the slope. So slope = 3.', difficulty: 'EASY' },
      { question: 'What is the sum of an arithmetic series with n terms?', optionA: 'n/2 × (2a + (n-1)d)', optionB: 'n × (a + l)/2', optionC: 'Both A and B', optionD: 'n × a × d', correctOption: 'C', explanation: 'Both formulas give the same result: n/2 × (first + last) = n/2 × (2a + (n-1)d).', difficulty: 'MEDIUM' },
      { question: "What is e (Euler's number) approximately equal to?", optionA: '2.718', optionB: '3.14159', optionC: '1.618', optionD: '2.236', correctOption: 'A', explanation: 'e ≈ 2.71828. It is the base of natural logarithms.', difficulty: 'EASY' },
    ],
  },
  {
    name: 'Marketing',
    department: 'BBA',
    icon: '📣',
    difficulty: 'MEDIUM',
    description: 'Consumer behavior, branding, digital marketing, and market strategy',
    questions: [
      { question: 'What is the product life cycle?', optionA: 'A product\'s expiry date', optionB: 'The stages a product goes through: introduction, growth, maturity, decline', optionC: 'The manufacturing process', optionD: 'A product\'s return policy', correctOption: 'B', explanation: 'The product life cycle describes the stages a product moves through from launch to withdrawal: Introduction, Growth, Maturity, and Decline.', difficulty: 'EASY' },
      { question: 'What is "brand equity"?', optionA: 'The financial value of a brand name', optionB: 'The value a brand adds to a product beyond its functional benefits', optionC: 'The cost of creating a brand', optionD: 'The number of brand loyal customers', correctOption: 'B', explanation: 'Brand equity is the premium value a company generates from a product with a recognizable name compared to a generic equivalent.', difficulty: 'MEDIUM' },
      { question: 'What is market segmentation?', optionA: 'Dividing the market into a single segment', optionB: 'Dividing a broad market into distinct subsets of consumers with common needs', optionC: 'Selling products only online', optionD: 'Targeting all consumers equally', correctOption: 'B', explanation: 'Market segmentation divides consumers into groups based on demographics, psychographics, behavior, or geography for targeted marketing.', difficulty: 'EASY' },
      { question: 'What is SEO in digital marketing?', optionA: 'Social Email Optimization', optionB: 'Search Engine Optimization — improving website visibility in organic search results', optionC: 'Sales Enhancement Operation', optionD: 'Search Engine Ordering', correctOption: 'B', explanation: 'SEO (Search Engine Optimization) involves optimizing a website\'s content, structure, and links to rank higher in search engine results pages.', difficulty: 'EASY' },
      { question: 'What is "consumer behavior" study?', optionA: 'Studying how consumers spend money', optionB: 'Understanding how individuals make decisions to purchase, use, and dispose of products', optionC: 'Measuring consumer debt', optionD: 'Tracking consumer complaints', correctOption: 'B', explanation: 'Consumer behavior studies the psychological, social, and physical processes that influence how people buy, use, and dispose of goods and services.', difficulty: 'MEDIUM' },
      { question: 'What is a "unique selling proposition" (USP)?', optionA: 'A discount offer', optionB: 'A factor that differentiates a product from its competitors', optionC: 'A universal product standard', optionD: 'A type of advertising', correctOption: 'B', explanation: 'USP is a clear statement that describes the unique benefit a product offers, how it solves a customer problem, and how it differs from competitors.', difficulty: 'MEDIUM' },
      { question: 'What is "content marketing"?', optionA: 'Selling content for profit', optionB: 'Creating and distributing valuable content to attract and retain a defined audience', optionC: 'Copying competitor content', optionD: 'Only writing blog posts', correctOption: 'B', explanation: 'Content marketing creates relevant articles, videos, podcasts, and other media to attract and engage a target audience, ultimately driving profitable customer action.', difficulty: 'MEDIUM' },
      { question: 'What is "customer lifetime value" (CLV)?', optionA: 'The age of a customer', optionB: 'The total revenue a business can expect from a single customer account over its lifetime', optionC: 'A loyalty program reward', optionD: 'The price of a product', correctOption: 'B', explanation: 'CLV predicts the total net profit a company can expect from a customer throughout their entire relationship with the business.', difficulty: 'HARD' },
      { question: 'What is the difference between marketing and selling?', optionA: 'They are the same', optionB: 'Marketing focuses on customer needs; selling focuses on converting products to cash', optionC: 'Selling is more important than marketing', optionD: 'Marketing only involves advertising', correctOption: 'B', explanation: 'Marketing identifies and satisfies customer needs (demand-oriented), while selling converts existing products into cash (product-oriented).', difficulty: 'HARD' },
      { question: 'What is "viral marketing"?', optionA: 'Marketing to sick people', optionB: 'A strategy where content spreads rapidly through word-of-mouth and online sharing', optionC: 'Marketing using viruses as logos', optionD: 'Marketing seasonal products', correctOption: 'B', explanation: 'Viral marketing creates content so compelling that consumers voluntarily share it, causing rapid, widespread exposure — like a virus — at minimal cost.', difficulty: 'MEDIUM' },
    ],
  },
  {
    name: 'Human Resources',
    department: 'BBA',
    icon: '👥',
    difficulty: 'MEDIUM',
    description: 'Recruitment, training, motivation, leadership, and HR management',
    questions: [
      { question: 'What is the primary purpose of HRM (Human Resource Management)?', optionA: 'To maximize profits', optionB: 'To manage people effectively for organizational and individual goals', optionC: 'To hire and fire employees', optionD: 'To handle only payroll', correctOption: 'B', explanation: 'HRM aims to manage people effectively, aligning employee goals with organizational objectives while ensuring employee well-being and development.', difficulty: 'EASY' },
      { question: 'What is the " Hawthorne Effect"?', optionA: 'Effect of lighting on productivity', optionB: 'Workers improve performance when they know they are being observed', optionC: 'Effect of salary on motivation', optionD: 'A theory about workplace accidents', correctOption: 'B', explanation: 'The Hawthorne Effect, discovered during studies at Hawthorne Works, found that workers\' productivity improved when they received attention, regardless of other factors.', difficulty: 'MEDIUM' },
      { question: 'What is "onboarding" in HR?', optionA: 'Firing an employee', optionB: 'The process of integrating a new employee into the organization', optionC: 'A training program for managers', optionD: 'An exit interview', correctOption: 'B', explanation: 'Onboarding is the structured process of helping new employees understand their role, company culture, policies, and team dynamics to ensure a smooth transition.', difficulty: 'EASY' },
      { question: 'According to Herzberg\'s Two-Factor Theory, which are "hygiene factors"?', optionA: 'Achievement and recognition', optionB: 'Salary, company policy, and working conditions', optionC: 'Growth and responsibility', optionD: 'Creativity and innovation', correctOption: 'B', explanation: 'Herzberg\'s hygiene factors (salary, policies, conditions) prevent dissatisfaction but don\'t motivate. Motivators (achievement, growth) actually drive satisfaction.', difficulty: 'MEDIUM' },
      { question: 'What is a "360-degree feedback" system?', optionA: 'Feedback from only the manager', optionB: 'Feedback collected from supervisors, peers, subordinates, and self', optionC: 'Annual performance review', optionD: 'Customer feedback only', correctOption: 'B', explanation: '360-degree feedback gathers performance input from multiple sources — managers, peers, direct reports, and self-assessment — for comprehensive evaluation.', difficulty: 'MEDIUM' },
      { question: 'What is the difference between recruitment and selection?', optionA: 'They are the same process', optionB: 'Recruitment attracts candidates; selection chooses the best from applicants', optionC: 'Selection comes before recruitment', optionD: 'Recruitment is for permanent staff only', correctOption: 'B', explanation: 'Recruitment is the process of finding and attracting potential candidates. Selection is the process of evaluating and choosing the most suitable candidate from the applicant pool.', difficulty: 'EASY' },
      { question: 'What is "job enrichment"?', optionA: 'Giving employees more pay', optionB: 'Adding more meaningful tasks and responsibilities to make work more rewarding', optionC: 'Reducing work hours', optionD: 'Changing job location', correctOption: 'B', explanation: 'Job enrichment involves adding depth to a job by giving workers more responsibility, autonomy, and growth opportunities to increase motivation.', difficulty: 'MEDIUM' },
      { question: 'What is the purpose of a "job description"?', optionA: 'To set employee salary', optionB: 'To outline duties, responsibilities, and requirements of a position', optionC: 'To evaluate employee performance', optionD: 'To describe the company history', correctOption: 'B', explanation: 'A job description clearly defines the role\'s title, duties, responsibilities, qualifications, reporting structure, and working conditions.', difficulty: 'EASY' },
      { question: 'What is "performance appraisal"?', optionA: 'A salary negotiation', optionB: 'A systematic evaluation of an employee\'s job performance and contributions', optionC: 'A hiring process', optionD: 'An exit procedure', correctOption: 'B', explanation: 'Performance appraisal is a formal process to evaluate an employee\'s work against set objectives, identifying strengths, areas for improvement, and development needs.', difficulty: 'EASY' },
      { question: 'What is "training needs analysis"?', optionA: 'Analyzing the training budget', optionB: 'Identifying gaps between current and required employee skills and knowledge', optionC: 'Evaluating trainer performance', optionD: 'Creating training materials', correctOption: 'B', explanation: 'Training Needs Analysis (TNA) identifies what training employees need by comparing current competencies with required skills for their roles or future roles.', difficulty: 'HARD' },
    ],
  },
  {
    name: 'Financial Accounting',
    department: 'BBA',
    icon: '💰',
    difficulty: 'MEDIUM',
    description: 'Balance sheet, income statement, depreciation, and financial principles',
    questions: [
      { question: 'What is the basic accounting equation?', optionA: 'Revenue - Expenses = Profit', optionB: 'Assets = Liabilities + Owner\'s Equity', optionC: 'Sales = Cost + Profit', optionD: 'Cash = Revenue - Expenses', correctOption: 'B', explanation: 'The fundamental accounting equation is Assets = Liabilities + Owner\'s Equity. It forms the basis for double-entry bookkeeping.', difficulty: 'EASY' },
      { question: 'What is an income statement also known as?', optionA: 'Balance Sheet', optionB: 'Profit and Loss Statement', optionC: 'Cash Flow Statement', optionD: 'Trial Balance', correctOption: 'B', explanation: 'An income statement (Profit and Loss Statement) shows a company\'s revenues, expenses, and profit/loss over a specific period.', difficulty: 'EASY' },
      { question: 'What is "depreciation" in accounting?', optionA: 'Increase in asset value', optionB: 'Systematic allocation of a tangible asset\'s cost over its useful life', optionC: 'Payment of debts', optionD: 'Cash received from sales', correctOption: 'B', explanation: 'Depreciation systematically spreads the cost of a fixed asset (like machinery) over its estimated useful life, reflecting wear and tear.', difficulty: 'MEDIUM' },
      { question: 'What is the "double-entry bookkeeping" system?', optionA: 'Keeping two sets of books', optionB: 'Every transaction affects at least two accounts with equal debits and credits', optionC: 'Recording transactions twice', optionD: 'A backup system', correctOption: 'B', explanation: 'In double-entry bookkeeping, every financial transaction is recorded in at least two accounts — one debit and one credit — ensuring the accounting equation always balances.', difficulty: 'MEDIUM' },
      { question: 'What is "accrual accounting"?', optionA: 'Recording only cash transactions', optionB: 'Recording revenues when earned and expenses when incurred, regardless of cash flow', optionC: 'Recording transactions at the end of the year', optionD: 'Estimating future profits', correctOption: 'B', explanation: 'Accrual accounting recognizes revenue when earned and expenses when incurred, providing a more accurate picture than cash accounting.', difficulty: 'MEDIUM' },
      { question: 'What is the formula for calculating depreciation using the straight-line method?', optionA: '(Cost × Rate) / 100', optionB: '(Cost - Salvage Value) / Useful Life', optionC: 'Cost / Rate', optionD: 'Cost × Useful Life', correctOption: 'B', explanation: 'Straight-line depreciation = (Cost of Asset - Salvage Value) / Useful Life. It allocates equal depreciation expense each year.', difficulty: 'MEDIUM' },
      { question: 'What is "working capital"?', optionA: 'The total capital invested', optionB: 'Current Assets minus Current Liabilities', optionC: 'Long-term debt', optionD: 'Shareholder equity', correctOption: 'B', explanation: 'Working capital = Current Assets - Current Liabilities. It measures a company\'s short-term financial health and operational efficiency.', difficulty: 'EASY' },
      { question: 'What is the "trial balance" used for?', optionA: 'To test employee performance', optionB: 'To verify that total debits equal total credits in the ledger', optionC: 'To calculate profit', optionD: 'To prepare budgets', correctOption: 'B', explanation: 'A trial balance lists all ledger accounts with their debit or credit balances to verify that total debits equal total credits, catching basic recording errors.', difficulty: 'MEDIUM' },
      { question: 'What is "goodwill" in accounting?', optionA: 'Employee satisfaction', optionB: 'An intangible asset representing the value of a business\'s reputation and brand', optionC: 'A type of loan', optionD: 'Charitable donations', correctOption: 'B', explanation: 'Goodwill is an intangible asset that arises when a company is purchased for more than the fair value of its net identifiable assets, representing brand value, customer loyalty, etc.', difficulty: 'HARD' },
      { question: 'What does "GAAP" stand for?', optionA: 'Generally Accepted Auditing Procedures', optionB: 'Generally Accepted Accounting Principles', optionC: 'Globally Applied Accounting Practices', optionD: 'General Accounting and Auditing Process', correctOption: 'B', explanation: 'GAAP (Generally Accepted Accounting Principles) is a collection of commonly followed accounting rules and standards used for financial reporting.', difficulty: 'EASY' },
    ],
  },
  {
    name: 'Entrepreneurship',
    department: 'BBA',
    icon: '🚀',
    difficulty: 'MEDIUM',
    description: 'Startups, business plans, funding, innovation, and venture creation',
    questions: [
      { question: 'What is an entrepreneur?', optionA: 'An employee of a large corporation', optionB: 'A person who creates and runs a new business, taking on financial risk', optionC: 'A government official', optionD: 'A financial analyst', correctOption: 'B', explanation: 'An entrepreneur is an individual who identifies an opportunity, creates a new venture, and assumes the risks and rewards of the business.', difficulty: 'EASY' },
      { question: 'What is a "business plan"?', optionA: 'A personal goal list', optionB: 'A written document describing the business idea, strategy, market, and financial projections', optionC: 'A tax filing document', optionD: 'An employment contract', correctOption: 'B', explanation: 'A business plan is a comprehensive document that outlines the business concept, market analysis, organizational structure, financial plan, and growth strategy.', difficulty: 'EASY' },
      { question: 'What is "bootstrapping" in startups?', optionA: 'A type of shoe', optionB: 'Building a company with minimal external funding, using personal savings and revenue', optionC: 'Taking large bank loans', optionD: 'Selling company shares publicly', correctOption: 'B', explanation: 'Bootstrapping means starting and growing a business using personal finances and operating revenues rather than seeking external investors or loans.', difficulty: 'MEDIUM' },
      { question: 'What is "venture capital"?', optionA: 'Money saved by employees', optionB: 'Funding provided by investors to startups with high growth potential in exchange for equity', optionC: 'Government grants only', optionD: 'Bank overdraft facility', correctOption: 'B', explanation: 'Venture capital is a form of private equity financing provided by VC firms to startups and early-stage companies with high growth potential, in exchange for ownership stake.', difficulty: 'MEDIUM' },
      { question: 'What is a "minimum viable product" (MVP)?', optionA: 'A cheap product', optionB: 'The simplest version of a product that can be released to test a business idea', optionC: 'A product with maximum features', optionD: 'A prototype only', correctOption: 'B', explanation: 'An MVP has just enough core features to be usable by early customers, allowing entrepreneurs to test assumptions and gather feedback with minimal investment.', difficulty: 'MEDIUM' },
      { question: 'What is "disruptive innovation"?', optionA: 'Creating minor improvements', optionB: 'A new innovation that creates a new market and value network, eventually displacing established firms', optionC: 'Copying existing products', optionD: 'Improving quality of luxury goods', correctOption: 'B', explanation: 'Disruptive innovation, a concept by Clayton Christensen, describes innovations that create new markets and value networks, eventually overtaking established market leaders.', difficulty: 'HARD' },
      { question: 'What is an "incubator" in the startup ecosystem?', optionA: 'A machine for startups', optionB: 'An organization that provides resources, mentoring, and workspace to early-stage startups', optionC: 'A government regulatory body', optionD: 'A type of venture capital firm', correctOption: 'B', explanation: 'A startup incubator offers early-stage companies office space, mentorship, networking, and sometimes seed funding to help them develop their business.', difficulty: 'MEDIUM' },
      { question: 'What is the "elevator pitch"?', optionA: 'A speech in an elevator', optionB: 'A brief, persuasive summary of a business idea deliverable in about 30-60 seconds', optionC: 'A sales presentation', optionD: 'A marketing jingle', correctOption: 'B', explanation: 'An elevator pitch is a concise, compelling overview of a business concept that can be delivered in the time of a short elevator ride, designed to spark interest.', difficulty: 'EASY' },
      { question: 'What is "equity financing"?', optionA: 'Borrowing money from a bank', optionB: 'Raising capital by selling ownership shares in the company', optionC: 'Using personal credit cards', optionD: 'Winning a business grant', correctOption: 'B', explanation: 'Equity financing involves selling a portion of ownership (shares) to investors in exchange for capital. Unlike debt, it does not require repayment but dilutes ownership.', difficulty: 'HARD' },
      { question: 'What is a "pivot" in startup terminology?', optionA: 'A dance move', optionB: 'A fundamental change in business strategy to adapt to market feedback', optionC: 'Shutting down the company', optionD: 'Expanding to new markets', correctOption: 'B', explanation: 'A pivot is a significant change in a startup\'s product, business model, or strategy based on learning from the market, aimed at finding a more viable path.', difficulty: 'MEDIUM' },
    ],
  },
];

export async function seedQuizData() {
  console.log('[Seed] Starting quiz data seeding...');

  for (const cat of CATEGORIES) {
    const category = await db.quizCategory.upsert({
      where: { id: `${cat.department}-${cat.name.toLowerCase().replace(/\s+/g, '-')}` },
      create: {
        id: `${cat.department}-${cat.name.toLowerCase().replace(/\s+/g, '-')}`,
        name: cat.name,
        department: cat.department,
        icon: cat.icon,
        difficulty: cat.difficulty,
        description: cat.description,
      },
      update: {},
    });

    for (const q of cat.questions) {
      await db.quizQuestion.upsert({
        where: { id: `${category.id}-${q.question.slice(0, 30).replace(/\s+/g, '-').toLowerCase()}` },
        create: {
          id: `${category.id}-${q.question.slice(0, 30).replace(/\s+/g, '-').toLowerCase()}`,
          categoryId: category.id,
          question: q.question,
          optionA: q.optionA,
          optionB: q.optionB,
          optionC: q.optionC,
          optionD: q.optionD,
          correctOption: q.correctOption,
          difficulty: q.difficulty,
          points: q.difficulty === 'EASY' ? 10 : q.difficulty === 'MEDIUM' ? 15 : 20,
        },
        update: {},
      });
    }

    console.log(`[Seed] ✓ ${cat.name} (${cat.department}): ${cat.questions.length} questions`);
  }

  console.log(`[Seed] ✓ Quiz data seeded successfully!`);
}
