// ══════════════════════════════════════════════════
// Memory Game Data — Card pair data for all 10 memory games
// ══════════════════════════════════════════════════
import type { MemoryCard } from '@/components/games/engines/MemoryEngine';

export const memoryGames: Record<string, MemoryCard[]> = {
  'memory-code-match': [
    { id: 'cm1', pairId: 'cm1', front: 'console.log()', back: 'Output to console' },
    { id: 'cm2', pairId: 'cm2', front: 'arr.push(x)', back: 'Add to end of array' },
    { id: 'cm3', pairId: 'cm3', front: 'arr.pop()', back: 'Remove from end' },
    { id: 'cm4', pairId: 'cm4', front: 'str.length', back: 'String length' },
    { id: 'cm5', pairId: 'cm5', front: 'Math.random()', back: 'Random 0-1' },
    { id: 'cm6', pairId: 'cm6', front: 'typeof x', back: 'Check data type' },
    { id: 'cm7', pairId: 'cm7', front: 'obj.keys()', back: 'Get object keys' },
    { id: 'cm8', pairId: 'cm8', front: 'JSON.parse()', back: 'Parse JSON string' },
  ],
  'memory-api-match': [
    { id: 'am1', pairId: 'am1', front: 'GET', back: 'Read data' },
    { id: 'am2', pairId: 'am2', front: 'POST', back: 'Create data' },
    { id: 'am3', pairId: 'am3', front: 'PUT', back: 'Update data (full)' },
    { id: 'am4', pairId: 'am4', front: 'PATCH', back: 'Update data (partial)' },
    { id: 'am5', pairId: 'am5', front: 'DELETE', back: 'Remove data' },
    { id: 'am6', pairId: 'am6', front: '200', back: 'OK' },
    { id: 'am7', pairId: 'am7', front: '404', back: 'Not Found' },
    { id: 'am8', pairId: 'am8', front: '500', back: 'Server Error' },
  ],
  'memory-emoji-decode': [
    { id: 'ed1', pairId: 'ed1', front: '🐍', back: 'Python' },
    { id: 'ed2', pairId: 'ed2', front: '⚡', back: 'JavaScript' },
    { id: 'ed3', pairId: 'ed3', front: '☕', back: 'Java' },
    { id: 'ed4', pairId: 'ed4', front: '🔧', back: 'C++' },
    { id: 'ed5', pairId: 'ed5', front: '🌐', back: 'HTML' },
    { id: 'ed6', pairId: 'ed6', front: '🎨', back: 'CSS' },
    { id: 'ed7', pairId: 'ed7', front: '🗄️', back: 'SQL' },
    { id: 'ed8', pairId: 'ed8', front: '🐳', back: 'Docker' },
  ],
  'memory-color-match': [
    { id: 'cl1', pairId: 'cl1', front: '#ff0000', back: 'Red' },
    { id: 'cl2', pairId: 'cl2', front: '#00ff00', back: 'Green' },
    { id: 'cl3', pairId: 'cl3', front: '#0000ff', back: 'Blue' },
    { id: 'cl4', pairId: 'cl4', front: '#ffff00', back: 'Yellow' },
    { id: 'cl5', pairId: 'cl5', front: '#ff00ff', back: 'Magenta' },
    { id: 'cl6', pairId: 'cl6', front: '#00ffff', back: 'Cyan' },
    { id: 'cl7', pairId: 'cl7', front: '#000000', back: 'Black' },
    { id: 'cl8', pairId: 'cl8', front: '#ffffff', back: 'White' },
  ],
  'memory-icon-match': [
    { id: 'ic1', pairId: 'ic1', front: '⚛️', back: 'React' },
    { id: 'ic2', pairId: 'ic2', front: '🟢', back: 'Node.js' },
    { id: 'ic3', pairId: 'ic3', front: '🔷', back: 'TypeScript' },
    { id: 'ic4', pairId: 'ic4', front: '🔥', back: 'Firebase' },
    { id: 'ic5', pairId: 'ic5', front: '▶️', back: 'Play' },
    { id: 'ic6', pairId: 'ic6', front: '📦', back: 'Webpack' },
    { id: 'ic7', pairId: 'ic7', front: '🦀', back: 'Rust' },
    { id: 'ic8', pairId: 'ic8', front: '🟣', back: 'Vite' },
  ],
  'memory-syntax-pairs': [
    { id: 'sp1', pairId: 'sp1', front: 'def func():', back: 'Python function' },
    { id: 'sp2', pairId: 'sp2', front: 'function fn() {}', back: 'JS function' },
    { id: 'sp3', pairId: 'sp3', front: 'void method() {}', back: 'Java method' },
    { id: 'sp4', pairId: 'sp4', front: 'print()', back: 'Python output' },
    { id: 'sp5', pairId: 'sp5', front: 'console.log()', back: 'JS output' },
    { id: 'sp6', pairId: 'sp6', front: 'System.out.println()', back: 'Java output' },
    { id: 'sp7', pairId: 'sp7', front: 'for i in range():', back: 'Python for loop' },
    { id: 'sp8', pairId: 'sp8', front: 'for (let i = 0;)', back: 'JS for loop' },
  ],
  'memory-bug-patterns': [
    { id: 'bp1', pairId: 'bp1', front: 'Off-by-one', back: 'range(n) vs range(n+1)' },
    { id: 'bp2', pairId: 'bp2', front: 'Null reference', back: 'Check for null first' },
    { id: 'bp3', pairId: 'bp3', front: '= vs ==', back: 'Assignment vs comparison' },
    { id: 'bp4', pairId: 'bp4', front: 'Infinite loop', back: 'Missing increment' },
    { id: 'bp5', pairId: 'bp5', front: 'Scope issue', back: 'var vs let' },
    { id: 'bp6', pairId: 'bp6', front: 'Type error', back: 'Wrong type conversion' },
    { id: 'bp7', pairId: 'bp7', front: 'Race condition', back: 'Concurrent access' },
    { id: 'bp8', pairId: 'bp8', front: 'Memory leak', back: 'Forgot to free/dispose' },
  ],
  'memory-terminal-cmds': [
    { id: 'tc1', pairId: 'tc1', front: 'ls', back: 'List files' },
    { id: 'tc2', pairId: 'tc2', front: 'cd', back: 'Change directory' },
    { id: 'tc3', pairId: 'tc3', front: 'pwd', back: 'Print working dir' },
    { id: 'tc4', pairId: 'tc4', front: 'mkdir', back: 'Make directory' },
    { id: 'tc5', pairId: 'tc5', front: 'rm', back: 'Remove file' },
    { id: 'tc6', pairId: 'tc6', front: 'cp', back: 'Copy file' },
    { id: 'tc7', pairId: 'tc7', front: 'mv', back: 'Move/rename file' },
    { id: 'tc8', pairId: 'tc8', front: 'cat', back: 'Display file content' },
  ],
  'memory-keyboard-shortcuts': [
    { id: 'ks1', pairId: 'ks1', front: 'Ctrl+C', back: 'Copy' },
    { id: 'ks2', pairId: 'ks2', front: 'Ctrl+V', back: 'Paste' },
    { id: 'ks3', pairId: 'ks3', front: 'Ctrl+Z', back: 'Undo' },
    { id: 'ks4', pairId: 'ks4', front: 'Ctrl+S', back: 'Save' },
    { id: 'ks5', pairId: 'ks5', front: 'Ctrl+P', back: 'Print/Find' },
    { id: 'ks6', pairId: 'ks6', front: 'Ctrl+F', back: 'Find' },
    { id: 'ks7', pairId: 'ks7', front: 'Alt+Tab', back: 'Switch windows' },
    { id: 'ks8', pairId: 'ks8', front: 'Ctrl+Shift+P', back: 'Command palette' },
  ],
  'memory-data-types': [
    { id: 'dt1', pairId: 'dt1', front: 'int', back: 'Integer number' },
    { id: 'dt2', pairId: 'dt2', front: 'float', back: 'Decimal number' },
    { id: 'dt3', pairId: 'dt3', front: 'string', back: 'Text' },
    { id: 'dt4', pairId: 'dt4', front: 'bool', back: 'True/False' },
    { id: 'dt5', pairId: 'dt5', front: 'array', back: 'Ordered collection' },
    { id: 'dt6', pairId: 'dt6', front: 'object', back: 'Key-value pairs' },
    { id: 'dt7', pairId: 'dt7', front: 'null', back: 'No value' },
    { id: 'dt8', pairId: 'dt8', front: 'void', back: 'No return type' },
  ],
};
