// ══════════════════════════════════════════════════
// Quiz Game Data — Questions for all 15 quiz games
// ══════════════════════════════════════════════════
import type { QuizQuestion } from '@/components/games/engines/QuizEngine';

export const quizQuestions: Record<string, QuizQuestion[]> = {
  'quiz-python': [
    { id: 'py1', question: 'What is the output of: x = 5; x += 3; print(x)?', options: ['5', '8', '3', 'Error'], correctAnswer: 'B', explanation: 'x += 3 means x = x + 3 = 8.', points: 10, timeLimit: 15 },
    { id: 'py2', question: 'Which keyword defines a function in Python?', options: ['function', 'func', 'def', 'define'], correctAnswer: 'C', explanation: 'Python uses "def" keyword.', points: 10, timeLimit: 10 },
    { id: 'py3', question: 'What does len([1,2,3]) return?', options: ['2', '3', '4', '6'], correctAnswer: 'B', explanation: 'The list has 3 elements.', points: 10, timeLimit: 10 },
    { id: 'py4', question: 'What does "hello"[0] return?', options: ['"h"', '"hello"', '"e"', 'Error'], correctAnswer: 'A', explanation: 'String indexing starts at 0.', points: 10, timeLimit: 10 },
    { id: 'py5', question: 'Which data structure uses key-value pairs?', options: ['List', 'Tuple', 'Dictionary', 'Set'], correctAnswer: 'C', explanation: 'Dicts store key-value pairs.', points: 10, timeLimit: 10 },
    { id: 'py6', question: 'What is the output of range(5)?', options: ['0-4', '1-5', '0-5', '1-4'], correctAnswer: 'A', explanation: 'range(5) generates 0,1,2,3,4.', points: 10, timeLimit: 15 },
    { id: 'py7', question: 'What does "break" do in a loop?', options: ['Skip iteration', 'Exit loop', 'Restart loop', 'Pause loop'], correctAnswer: 'B', explanation: '"break" exits the loop.', points: 10, timeLimit: 10 },
    { id: 'py8', question: 'What is the type of 3 / 2 in Python 3?', options: ['int', 'float', 'double', 'str'], correctAnswer: 'B', explanation: '/ always returns float in Python 3.', points: 15, timeLimit: 15 },
    { id: 'py9', question: 'What is a list comprehension?', options: ['A way to create lists', 'A sorting algorithm', 'A type of loop', 'An error handler'], correctAnswer: 'A', explanation: 'List comprehensions provide a concise way to create lists.', points: 10, timeLimit: 15 },
    { id: 'py10', question: 'What does "pass" do?', options: ['Raises error', 'Does nothing (placeholder)', 'Breaks loop', 'Returns None'], correctAnswer: 'B', explanation: '"pass" is a null statement placeholder.', points: 10, timeLimit: 10 },
  ],
  'quiz-javascript': [
    { id: 'js1', question: 'Which keyword creates a block-scoped variable?', options: ['var', 'let', 'both let and const', 'function'], correctAnswer: 'C', explanation: 'Both let and const are block-scoped.', points: 10, timeLimit: 15 },
    { id: 'js2', question: 'What is typeof null?', options: ['"null"', '"undefined"', '"object"', '"boolean"'], correctAnswer: 'C', explanation: 'This is a famous JS bug.', points: 15, timeLimit: 15 },
    { id: 'js3', question: 'What does [1,2,3].push(4) return?', options: ['4', '[1,2,3,4]', '3', 'undefined'], correctAnswer: 'A', explanation: 'push() returns the new length of the array.', points: 15, timeLimit: 15 },
    { id: 'js4', question: 'What is an arrow function?', options: ['function() {}', '() => {}', 'func() {}', 'lambda() {}'], correctAnswer: 'B', explanation: 'Arrow functions use => syntax.', points: 10, timeLimit: 10 },
    { id: 'js5', question: 'Which loop guarantees at least one execution?', options: ['for', 'while', 'do...while', 'for...in'], correctAnswer: 'C', explanation: 'do...while executes body before checking condition.', points: 10, timeLimit: 15 },
    { id: 'js6', question: 'What does "===" check?', options: ['Value only', 'Type only', 'Value and type', 'Reference'], correctAnswer: 'C', explanation: '=== checks both value and type (strict equality).', points: 10, timeLimit: 10 },
    { id: 'js7', question: 'What does Array.isArray([]) return?', options: ['true', 'false', '"array"', 'undefined'], correctAnswer: 'A', explanation: 'It returns true for arrays.', points: 10, timeLimit: 10 },
    { id: 'js8', question: 'How do you create a Promise?', options: ['new Promise()', 'Promise()', 'createPromise()', 'makePromise()'], correctAnswer: 'A', explanation: 'Promises are created with the new keyword.', points: 10, timeLimit: 15 },
    { id: 'js9', question: 'What does JSON.stringify() do?', options: ['Parses JSON', 'Converts to JSON string', 'Creates object', 'Validates JSON'], correctAnswer: 'B', explanation: 'It converts a JS value to a JSON string.', points: 10, timeLimit: 10 },
    { id: 'js10', question: 'What is async/await used for?', options: ['Animation', 'Handling async operations', 'Error handling', 'State management'], correctAnswer: 'B', explanation: 'async/await simplifies Promise-based async code.', points: 15, timeLimit: 15 },
  ],
  'quiz-java': [
    { id: 'jv1', question: 'Which is correct integer declaration?', options: ['int x = 5;', 'var x = 5;', 'integer x = 5;', 'x := 5;'], correctAnswer: 'A', explanation: 'Java uses typed declarations: int x = 5;', points: 10, timeLimit: 10 },
    { id: 'jv2', question: 'What is the default value of a boolean field?', options: ['true', 'false', 'null', '0'], correctAnswer: 'B', explanation: 'Boolean fields default to false.', points: 10, timeLimit: 10 },
    { id: 'jv3', question: 'What keyword is used for inheritance?', options: ['inherits', 'implements', 'extends', 'super'], correctAnswer: 'C', explanation: 'Java uses "extends" for class inheritance.', points: 15, timeLimit: 15 },
    { id: 'jv4', question: 'Can a class extend multiple classes?', options: ['Yes', 'No, only one', 'Up to 3', 'Yes with multi keyword'], correctAnswer: 'B', explanation: 'Java supports single class inheritance.', points: 20, timeLimit: 15 },
    { id: 'jv5', question: 'How do you compare strings?', options: ['str1 == str2', 'str1.equals(str2)', 'str1 === str2', 'compare(str1, str2)'], correctAnswer: 'B', explanation: 'Use .equals() for value comparison.', points: 15, timeLimit: 15 },
    { id: 'jv6', question: 'What is the entry point of a Java program?', options: ['start()', 'init()', 'main()', 'run()'], correctAnswer: 'C', explanation: 'public static void main(String[] args)', points: 10, timeLimit: 10 },
    { id: 'jv7', question: 'What does "final" keyword do?', options: ['Makes variable mutable', 'Prevents modification', 'Creates interface', 'Adds logging'], correctAnswer: 'B', explanation: 'final makes variables, methods, or classes unchangeable.', points: 10, timeLimit: 15 },
    { id: 'jv8', question: 'What is an interface in Java?', options: ['A concrete class', 'A contract of methods', 'A variable type', 'A loop construct'], correctAnswer: 'B', explanation: 'Interfaces define method signatures that classes must implement.', points: 15, timeLimit: 15 },
  ],
  'quiz-cpp': [
    { id: 'cp1', question: 'Which is correct float declaration?', options: ['float x = 3.14;', 'Float x = 3.14;', 'f x = 3.14;', 'decimal x = 3.14;'], correctAnswer: 'A', explanation: 'C++ uses lowercase float.', points: 10, timeLimit: 10 },
    { id: 'cp2', question: 'What does & mean in a parameter?', options: ['Logical AND', 'Bitwise AND', 'Pass by reference', 'Address of'], correctAnswer: 'C', explanation: 'In parameters, & means pass by reference.', points: 10, timeLimit: 10 },
    { id: 'cp3', question: 'Which STL container provides key-value pairs?', options: ['vector', 'map', 'set', 'list'], correctAnswer: 'B', explanation: 'std::map provides key-value pairs.', points: 15, timeLimit: 15 },
    { id: 'cp4', question: 'What is the time complexity of binary search?', options: ['O(n)', 'O(log n)', 'O(1)', 'O(n²)'], correctAnswer: 'B', explanation: 'Binary search halves the search space each step.', points: 15, timeLimit: 15 },
    { id: 'cp5', question: 'What is a pointer?', options: ['A reference type', 'A variable storing memory address', 'A loop counter', 'A function type'], correctAnswer: 'B', explanation: 'Pointers store memory addresses.', points: 10, timeLimit: 10 },
    { id: 'cp6', question: 'What does "delete" do?', options: ['Removes variable', 'Frees heap memory', 'Deletes file', 'Removes array element'], correctAnswer: 'B', explanation: 'delete frees memory allocated with new.', points: 10, timeLimit: 15 },
    { id: 'cp7', question: 'What is a template?', options: ['A code pattern', 'Generic programming construct', 'A UI layout', 'A data format'], correctAnswer: 'B', explanation: 'Templates enable generic programming in C++.', points: 15, timeLimit: 15 },
    { id: 'cp8', question: 'What header is needed for std::string?', options: ['<string>', '<cstring>', '<String>', '<text>'], correctAnswer: 'A', explanation: '#include <string> is needed.', points: 10, timeLimit: 10 },
  ],
  'quiz-html': [
    { id: 'ht1', question: 'What does HTML stand for?', options: ['Hyper Text Markup Language', 'Home Tool Markup Language', 'Hyperlinks and Text Markup Language', 'Hyper Tool Multi Language'], correctAnswer: 'A', explanation: 'HTML = HyperText Markup Language.', points: 10, timeLimit: 10 },
    { id: 'ht2', question: 'Which tag creates a hyperlink?', options: ['<link>', '<a>', '<href>', '<url>'], correctAnswer: 'B', explanation: '<a> tag with href attribute creates links.', points: 10, timeLimit: 10 },
    { id: 'ht3', question: 'Which tag is used for the largest heading?', options: ['<heading>', '<h6>', '<h1>', '<head>'], correctAnswer: 'C', explanation: '<h1> is the largest heading level.', points: 10, timeLimit: 10 },
    { id: 'ht4', question: 'What is a semantic HTML element?', options: ['Any HTML tag', 'Tags that describe meaning', 'Styling tags', 'Script tags'], correctAnswer: 'B', explanation: 'Semantic elements like <article>, <nav> describe their meaning.', points: 10, timeLimit: 15 },
    { id: 'ht5', question: 'Which attribute specifies an image source?', options: ['link', 'src', 'href', 'url'], correctAnswer: 'B', explanation: 'src attribute specifies image URL.', points: 10, timeLimit: 10 },
    { id: 'ht6', question: 'What does the <form> tag do?', options: ['Creates a shape', 'Creates user input form', 'Formats text', 'Creates a frame'], correctAnswer: 'B', explanation: '<form> wraps user input elements.', points: 10, timeLimit: 10 },
    { id: 'ht7', question: 'What is the correct HTML for a line break?', options: ['<break>', '<lb>', '<br>', '<newline>'], correctAnswer: 'C', explanation: '<br> inserts a line break.', points: 10, timeLimit: 10 },
    { id: 'ht8', question: 'Which input type creates a checkbox?', options: ['type="check"', 'type="checkbox"', 'type="box"', 'type="tick"'], correctAnswer: 'B', explanation: 'type="checkbox" creates a checkbox.', points: 10, timeLimit: 10 },
  ],
  'quiz-css': [
    { id: 'cs1', question: 'What does CSS stand for?', options: ['Creative Style Sheets', 'Cascading Style Sheets', 'Computer Style Sheets', 'Colorful Style Sheets'], correctAnswer: 'B', explanation: 'CSS = Cascading Style Sheets.', points: 10, timeLimit: 10 },
    { id: 'cs2', question: 'Which property changes text color?', options: ['font-color', 'text-color', 'color', 'foreground-color'], correctAnswer: 'C', explanation: 'The "color" property sets text color.', points: 10, timeLimit: 10 },
    { id: 'cs3', question: 'What is Flexbox?', options: ['A layout module', 'A framework', 'A language', 'A database'], correctAnswer: 'A', explanation: 'Flexbox is a CSS layout module.', points: 10, timeLimit: 15 },
    { id: 'cs4', question: 'What does "display: grid" do?', options: ['Shows grid lines', 'Creates grid layout', 'Shows table', 'Creates columns'], correctAnswer: 'B', explanation: 'display: grid creates a grid container.', points: 10, timeLimit: 15 },
    { id: 'cs5', question: 'What does "position: absolute" do?', options: ['Fixes position', 'Positions relative to viewport', 'Positions relative to nearest positioned ancestor', 'Removes element'], correctAnswer: 'C', explanation: 'Absolute positioning is relative to nearest positioned parent.', points: 15, timeLimit: 15 },
    { id: 'cs6', question: 'What is a CSS selector?', options: ['A filter', 'Pattern to select elements', 'A variable', 'A function'], correctAnswer: 'B', explanation: 'Selectors target HTML elements for styling.', points: 10, timeLimit: 10 },
    { id: 'cs7', question: 'What does "z-index" control?', options: ['Width', 'Stacking order', 'Zoom level', 'Height'], correctAnswer: 'B', explanation: 'z-index controls element stacking order.', points: 10, timeLimit: 10 },
    { id: 'cs8', question: 'What is a media query?', options: ['A database query', 'Responsive design rule', 'An API call', 'A search filter'], correctAnswer: 'B', explanation: 'Media queries apply styles based on device characteristics.', points: 10, timeLimit: 15 },
  ],
  'quiz-sql': [
    { id: 'sq1', question: 'What does SELECT do?', options: ['Inserts data', 'Retrieves data', 'Updates data', 'Deletes data'], correctAnswer: 'B', explanation: 'SELECT retrieves data from a database.', points: 10, timeLimit: 10 },
    { id: 'sq2', question: 'What is a JOIN?', options: ['Combines tables', 'Creates table', 'Deletes table', 'Renames table'], correctAnswer: 'A', explanation: 'JOIN combines rows from multiple tables.', points: 15, timeLimit: 15 },
    { id: 'sq3', question: 'What does WHERE clause do?', options: ['Orders results', 'Filters results', 'Groups results', 'Limits results'], correctAnswer: 'B', explanation: 'WHERE filters records based on conditions.', points: 10, timeLimit: 10 },
    { id: 'sq4', question: 'What is a primary key?', options: ['A foreign reference', 'Unique identifier for each row', 'A password', 'A default value'], correctAnswer: 'B', explanation: 'Primary key uniquely identifies each record.', points: 10, timeLimit: 15 },
    { id: 'sq5', question: 'What does GROUP BY do?', options: ['Sorts results', 'Groups rows for aggregate functions', 'Creates groups', 'Filters groups'], correctAnswer: 'B', explanation: 'GROUP BY groups rows that have the same values.', points: 15, timeLimit: 15 },
    { id: 'sq6', question: 'What is an index?', options: ['A list', 'A data structure to speed up queries', 'A key', 'A constraint'], correctAnswer: 'B', explanation: 'Indexes speed up data retrieval operations.', points: 15, timeLimit: 15 },
    { id: 'sq7', question: 'What does DISTINCT do?', options: ['Joins tables', 'Returns unique values', 'Deletes duplicates', 'Orders data'], correctAnswer: 'B', explanation: 'DISTINCT removes duplicate rows from results.', points: 10, timeLimit: 10 },
    { id: 'sq8', question: 'What is a subquery?', options: ['A query inside another query', 'A query result', 'A query plan', 'A query cache'], correctAnswer: 'A', explanation: 'A subquery is a query nested inside another query.', points: 15, timeLimit: 15 },
  ],
  'quiz-git': [
    { id: 'gt1', question: 'What does "git init" do?', options: ['Starts a server', 'Initializes a repository', 'Creates a branch', 'Commits changes'], correctAnswer: 'B', explanation: 'git init creates a new Git repository.', points: 10, timeLimit: 10 },
    { id: 'gt2', question: 'What does "git clone" do?', options: ['Copies a file', 'Creates a copy of a remote repository', 'Branches code', 'Merges code'], correctAnswer: 'B', explanation: 'git clone copies a remote repository locally.', points: 10, timeLimit: 10 },
    { id: 'gt3', question: 'What is a branch?', options: ['A file', 'Independent line of development', 'A server', 'A tag'], correctAnswer: 'B', explanation: 'Branches allow parallel development.', points: 10, timeLimit: 15 },
    { id: 'gt4', question: 'What does "git merge" do?', options: ['Deletes a branch', 'Combines branches', 'Creates a branch', 'Checks out a branch'], correctAnswer: 'B', explanation: 'git merge combines two branches.', points: 10, timeLimit: 10 },
    { id: 'gt5', question: 'What is "git stash"?', options: ['Deletes changes', 'Temporarily stores uncommitted changes', 'Saves permanently', 'Creates a branch'], correctAnswer: 'B', explanation: 'stash temporarily shelves changes.', points: 15, timeLimit: 15 },
    { id: 'gt6', question: 'What does "git pull" do?', options: ['Pushes code', 'Fetches and merges remote changes', 'Creates PR', 'Deletes remote'], correctAnswer: 'B', explanation: 'git pull = git fetch + git merge.', points: 10, timeLimit: 10 },
    { id: 'gt7', question: 'What is a commit?', options: ['A save point in history', 'A branch', 'A file', 'A server'], correctAnswer: 'A', explanation: 'A commit saves a snapshot of changes.', points: 10, timeLimit: 10 },
    { id: 'gt8', question: 'What does "git rebase" do?', options: ['Rebases colors', 'Moves/reapplies commits onto another base', 'Creates base', 'Deletes base'], correctAnswer: 'B', explanation: 'Rebase replays commits on a different base.', points: 15, timeLimit: 15 },
  ],
  'quiz-docker': [
    { id: 'dk1', question: 'What is a Docker container?', options: ['A VM', 'Lightweight standalone package', 'A file format', 'A server'], correctAnswer: 'B', explanation: 'Containers package application and dependencies.', points: 10, timeLimit: 15 },
    { id: 'dk2', question: 'What is a Dockerfile?', options: ['A documentation file', 'Instructions to build an image', 'A config file', 'A log file'], correctAnswer: 'B', explanation: 'Dockerfile contains build instructions.', points: 10, timeLimit: 15 },
    { id: 'dk3', question: 'What does "docker run" do?', options: ['Stops container', 'Creates and starts a container', 'Builds image', 'Lists containers'], correctAnswer: 'B', explanation: 'docker run creates and starts a new container.', points: 10, timeLimit: 15 },
    { id: 'dk4', question: 'What is Docker Compose?', options: ['A language', 'Multi-container orchestration tool', 'A container runtime', 'A package manager'], correctAnswer: 'B', explanation: 'Compose defines and runs multi-container apps.', points: 15, timeLimit: 15 },
    { id: 'dk5', question: 'What is a Docker image?', options: ['A running container', 'A template for creating containers', 'A screenshot', 'A backup'], correctAnswer: 'B', explanation: 'Images are read-only templates for containers.', points: 10, timeLimit: 15 },
    { id: 'dk6', question: 'What does "docker build" do?', options: ['Runs container', 'Creates image from Dockerfile', 'Downloads image', 'Deletes image'], correctAnswer: 'B', explanation: 'build creates an image from Dockerfile.', points: 10, timeLimit: 15 },
  ],
  'quiz-react': [
    { id: 'rc1', question: 'What is a React Hook?', options: ['A fishing tool', 'Functions that let you use state in function components', 'A CSS feature', 'A routing tool'], correctAnswer: 'B', explanation: 'Hooks let you use React features in function components.', points: 10, timeLimit: 15 },
    { id: 'rc2', question: 'What does useState return?', options: ['An object', 'An array [value, setter]', 'A promise', 'A string'], correctAnswer: 'B', explanation: 'useState returns [currentValue, setterFunction].', points: 10, timeLimit: 15 },
    { id: 'rc3', question: 'What is JSX?', options: ['A CSS framework', 'JavaScript XML syntax extension', 'A database', 'A server language'], correctAnswer: 'B', explanation: 'JSX is a syntax extension for JavaScript.', points: 10, timeLimit: 10 },
    { id: 'rc4', question: 'What does useEffect do?', options: ['Creates styles', 'Performs side effects in function components', 'Manages state', 'Handles routing'], correctAnswer: 'B', explanation: 'useEffect handles side effects like data fetching.', points: 15, timeLimit: 15 },
    { id: 'rc5', question: 'What is the Virtual DOM?', options: ['A real DOM copy', 'Lightweight representation of real DOM', 'A CSS engine', 'A server'], correctAnswer: 'B', explanation: 'Virtual DOM is an in-memory representation of real DOM.', points: 10, timeLimit: 15 },
    { id: 'rc6', question: 'What does "key" prop do in lists?', options: ['Adds password', 'Helps React identify which items changed', 'Creates animation', 'Adds styling'], correctAnswer: 'B', explanation: 'Keys help React efficiently update lists.', points: 10, timeLimit: 15 },
    { id: 'rc7', question: 'What is React Router?', options: ['A CSS framework', 'Routing library for React', 'A database', 'A testing tool'], correctAnswer: 'B', explanation: 'React Router handles client-side routing.', points: 10, timeLimit: 10 },
    { id: 'rc8', question: 'What is "prop drilling"?', options: ['A construction technique', 'Passing props through multiple levels', 'A performance issue', 'A React pattern'], correctAnswer: 'B', explanation: 'Prop drilling is passing props down nested components.', points: 15, timeLimit: 15 },
  ],
  'quiz-ds': [
    { id: 'ds1', question: 'What is the time complexity of array access?', options: ['O(n)', 'O(log n)', 'O(1)', 'O(n²)'], correctAnswer: 'C', explanation: 'Array access by index is O(1).', points: 10, timeLimit: 15 },
    { id: 'ds2', question: 'What is a stack?', options: ['A queue', 'LIFO data structure', 'A tree', 'A graph'], correctAnswer: 'B', explanation: 'Stack is Last In, First Out.', points: 10, timeLimit: 10 },
    { id: 'ds3', question: 'What is a linked list?', options: ['Contiguous memory', 'Nodes with pointers', 'A type of array', 'A tree structure'], correctAnswer: 'B', explanation: 'Linked lists have nodes connected by pointers.', points: 10, timeLimit: 15 },
    { id: 'ds4', question: 'What is the worst case for quicksort?', options: ['O(n log n)', 'O(n²)', 'O(n)', 'O(log n)'], correctAnswer: 'B', explanation: 'Quicksort worst case is O(n²) when pivot is smallest/largest.', points: 15, timeLimit: 15 },
    { id: 'ds5', question: 'What is a hash table?', options: ['An encrypted table', 'Key-value store with O(1) average lookup', 'A sorting structure', 'A tree type'], correctAnswer: 'B', explanation: 'Hash tables use hash functions for O(1) average access.', points: 15, timeLimit: 15 },
    { id: 'ds6', question: 'What is BFS?', options: ['Best First Search', 'Breadth-First Search', 'Binary File Search', 'Boolean Function Search'], correctAnswer: 'B', explanation: 'BFS explores nodes level by level.', points: 10, timeLimit: 15 },
    { id: 'ds7', question: 'What is a binary tree?', options: ['A tree with 2 children max per node', 'A tree with 2 roots', 'A sorted array', 'A linked list'], correctAnswer: 'A', explanation: 'Binary tree nodes have at most 2 children.', points: 10, timeLimit: 10 },
    { id: 'ds8', question: 'What is dynamic programming?', options: ['Changing code at runtime', 'Optimization by breaking into subproblems', 'Parallel programming', 'Object-oriented programming'], correctAnswer: 'B', explanation: 'DP solves complex problems by breaking into overlapping subproblems.', points: 15, timeLimit: 15 },
  ],
  'quiz-algo': [
    { id: 'al1', question: 'What is the time complexity of merge sort?', options: ['O(n)', 'O(n log n)', 'O(n²)', 'O(log n)'], correctAnswer: 'B', explanation: 'Merge sort consistently runs in O(n log n).', points: 10, timeLimit: 15 },
    { id: 'al2', question: 'What is a greedy algorithm?', options: ['Uses lots of memory', 'Makes locally optimal choices', 'Tries all possibilities', 'Random approach'], correctAnswer: 'B', explanation: 'Greedy algorithms make the best local choice at each step.', points: 15, timeLimit: 15 },
    { id: 'al3', question: 'What is recursion?', options: ['A loop', 'Function calling itself', 'A type of array', 'A sorting method'], correctAnswer: 'B', explanation: 'Recursion is when a function calls itself.', points: 10, timeLimit: 10 },
    { id: 'al4', question: 'What is the difference between BFS and DFS?', options: ['Speed', 'BFS uses queue, DFS uses stack', 'Memory usage', 'Language'], correctAnswer: 'B', explanation: 'BFS uses queue (level order), DFS uses stack (depth order).', points: 15, timeLimit: 15 },
    { id: 'al5', question: 'What is Dijkstra\'s algorithm?', options: ['Sorting algorithm', 'Shortest path algorithm', 'Searching algorithm', 'Encryption algorithm'], correctAnswer: 'B', explanation: 'Dijkstra finds shortest paths in weighted graphs.', points: 15, timeLimit: 15 },
    { id: 'al6', question: 'What is a stable sort?', options: ['Fast sort', 'Preserves relative order of equal elements', 'Memory-efficient sort', 'Parallel sort'], correctAnswer: 'B', explanation: 'Stable sorts maintain the relative order of equal elements.', points: 10, timeLimit: 15 },
  ],
  'quiz-networking': [
    { id: 'nw1', question: 'What does DNS do?', options: ['Sends emails', 'Translates domain names to IP addresses', 'Encrypts data', 'Compresses files'], correctAnswer: 'B', explanation: 'DNS resolves domain names to IP addresses.', points: 10, timeLimit: 15 },
    { id: 'nw2', question: 'What is TCP?', options: ['A programming language', 'Reliable transport protocol', 'A database', 'A framework'], correctAnswer: 'B', explanation: 'TCP provides reliable, ordered data delivery.', points: 10, timeLimit: 15 },
    { id: 'nw3', question: 'What port does HTTP use?', options: ['21', '22', '80', '443'], correctAnswer: 'C', explanation: 'HTTP uses port 80 by default.', points: 10, timeLimit: 10 },
    { id: 'nw4', question: 'What is HTTPS?', options: ['Faster HTTP', 'HTTP with encryption (TLS/SSL)', 'HTTP for streaming', 'HTTP for files'], correctAnswer: 'B', explanation: 'HTTPS adds encryption layer to HTTP.', points: 10, timeLimit: 10 },
    { id: 'nw5', question: 'What is an IP address?', options: ['A web address', 'Unique device identifier on a network', 'A password', 'An email'], correctAnswer: 'B', explanation: 'IP addresses uniquely identify devices on networks.', points: 10, timeLimit: 15 },
    { id: 'nw6', question: 'What is a subnet mask?', options: ['A facial covering for networks', 'Defines network/host portions of IP', 'An encryption key', 'A firewall rule'], correctAnswer: 'B', explanation: 'Subnet masks separate network and host parts of IP addresses.', points: 15, timeLimit: 15 },
  ],
  'quiz-os': [
    { id: 'os1', question: 'What is a process?', options: ['A thread', 'Running program instance', 'A file', 'A device'], correctAnswer: 'B', explanation: 'A process is an executing program instance.', points: 10, timeLimit: 15 },
    { id: 'os2', question: 'What is the difference between process and thread?', options: ['Speed', 'Threads share memory, processes don\'t', 'Nothing', 'Size only'], correctAnswer: 'B', explanation: 'Threads of same process share memory; processes have separate memory.', points: 15, timeLimit: 15 },
    { id: 'os3', question: 'What is a deadlock?', options: ['A locked door', 'When processes wait for each other indefinitely', 'A slow process', 'A crashed program'], correctAnswer: 'B', explanation: 'Deadlock occurs when processes block each other permanently.', points: 15, timeLimit: 15 },
    { id: 'os4', question: 'What is virtual memory?', options: ['Fake memory', 'Using disk as extension of RAM', 'Cloud storage', 'Cache memory'], correctAnswer: 'B', explanation: 'Virtual memory uses disk space to extend available RAM.', points: 15, timeLimit: 15 },
    { id: 'os5', question: 'What is a page fault?', options: ['A torn page', 'When accessed data is not in RAM', 'A printing error', 'A web error'], correctAnswer: 'B', explanation: 'Page fault occurs when data needs to be loaded from disk to RAM.', points: 15, timeLimit: 15 },
    { id: 'os6', question: 'What is a context switch?', options: ['Switching tabs', 'OS saving/restoring CPU state for process switch', 'Changing network', 'Updating software'], correctAnswer: 'B', explanation: 'Context switch saves and restores state when switching processes.', points: 15, timeLimit: 15 },
  ],
  'quiz-cybersecurity': [
    { id: 'cy1', question: 'What is encryption?', options: ['Encoding images', 'Converting data to unreadable format', 'Compression', 'Deletion'], correctAnswer: 'B', explanation: 'Encryption converts data to ciphertext.', points: 10, timeLimit: 15 },
    { id: 'cy2', question: 'What is phishing?', options: ['Fishing game', 'Social engineering attack via fake messages', 'Network protocol', 'Debugging technique'], correctAnswer: 'B', explanation: 'Phishing tricks users into revealing sensitive info.', points: 10, timeLimit: 15 },
    { id: 'cy3', question: 'What is SQL injection?', options: ['Adding SQL features', 'Inserting malicious SQL queries through input', 'A database tool', 'A migration tool'], correctAnswer: 'B', explanation: 'SQL injection exploits unsanitized input to run malicious SQL.', points: 15, timeLimit: 15 },
    { id: 'cy4', question: 'What is HTTPS?', options: ['HTML over satellite', 'HTTP with TLS encryption', 'High-speed HTTP', 'HTTP server'], correctAnswer: 'B', explanation: 'HTTPS uses TLS to encrypt HTTP traffic.', points: 10, timeLimit: 10 },
    { id: 'cy5', question: 'What is a firewall?', options: ['A physical wall', 'Network security system filtering traffic', 'A heater', 'A power supply'], correctAnswer: 'B', explanation: 'Firewalls filter incoming and outgoing network traffic.', points: 10, timeLimit: 15 },
    { id: 'cy6', question: 'What is 2FA?', options: ['2 Factor Authentication', 'Two Fast Actions', '2 File Access', '2 Format Audio'], correctAnswer: 'A', explanation: '2FA requires two forms of identity verification.', points: 10, timeLimit: 10 },
  ],
};
